-- Complete FAQ Translation for German, Polish, Danish, and Swedish
-- Adding remaining 62+ FAQs for each language to match English content

-- German FAQ Translations (de)
INSERT INTO public.faqs (language, question, answer_short, answer_long, slug, category, tags, keywords, voice_queries, target_areas, property_types, meta_title, meta_description, is_featured, sort_order) VALUES

-- Buying Process - German
('de', 'Wie lange dauert der Immobilienkaufprozess in Spanien?', 'Der Immobilienkaufprozess in Spanien dauert normalerweise 8-12 Wochen ab der Angebotannahme.', 'Der vollständige Immobilienkaufprozess in Spanien umfasst mehrere Phasen: Angebotannahme (1-2 Wochen), Reservierungsvertrag und Anzahlung (1 Woche), Due Diligence und Rechtsprüfung (3-4 Wochen), Hypothekantragsbearbeitung falls erforderlich (4-6 Wochen), und abschließende notarielle Beurkundung (1-2 Wochen). DelSolPrimeHomes begleitet Sie durch jeden Schritt.', 'wie-lange-dauert-immobilienkauf-spanien-de', 'buying-process', ARRAY['Zeitrahmen', 'Kaufprozess', 'Spanien'], ARRAY['Immobilienkauf', 'Zeitrahmen', 'Spanien', 'Prozess'], ARRAY['Wie lange dauert es, eine Immobilie in Spanien zu kaufen', 'Zeitrahmen für Immobilienkauf Spanien'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['Villa', 'Apartment', 'Townhouse'], 'Immobilienkauf Spanien: Zeitrahmen und Prozess | DelSolPrimeHomes', 'Erfahren Sie, wie lange der Immobilienkaufprozess in Spanien dauert. Kompletter Guide mit Zeitrahmen für jeden Schritt des Kaufprozesses.', false, 1),

('de', 'Welche Steuern fallen beim Immobilienkauf in Spanien an?', 'Die Hauptsteuern sind ITP (6-10%), Notar- und Registergebühren (1-2%) und eventuelle Hypothekensteuern.', 'Beim Immobilienkauf in Spanien fallen verschiedene Steuern und Gebühren an: Übertragungssteuer (ITP) von 6-10% je nach Autonomer Gemeinschaft, Notar- und Grundbuchgebühren (1-2% des Kaufpreises), Anwaltskosten (1-1.5%), Hypothekensteuern falls zutreffend (0.5-1%), und eventuelle Mehrwertsteuer (10%) bei Neubauten. DelSolPrimeHomes erstellt transparente Kostenschätzungen.', 'welche-steuern-immobilienkauf-spanien-de', 'buying-process', ARRAY['Steuern', 'Kosten', 'Immobilienkauf'], ARRAY['Steuern', 'ITP', 'Übertragungssteuer', 'Kosten'], ARRAY['Welche Steuern muss ich beim Immobilienkauf in Spanien zahlen', 'Kosten für Immobilienkauf Spanien'], ARRAY['Costa del Sol', 'Andalusien'], ARRAY['Alle Immobilientypen'], 'Steuern beim Immobilienkauf in Spanien | Kompletter Guide', 'Vollständiger Überblick über alle Steuern und Gebühren beim Immobilienkauf in Spanien. ITP, Notargebühren und weitere Kosten erklärt.', true, 2),

('de', 'Kann ich als Nicht-EU-Bürger Immobilien in Spanien kaufen?', 'Ja, Nicht-EU-Bürger können problemlos Immobilien in Spanien erwerben mit denselben Rechten wie EU-Bürger.', 'Nicht-EU-Bürger haben die gleichen Immobilienerwerbsrechte in Spanien wie EU-Bürger. Sie benötigen lediglich eine NIE-Nummer (Número de Identificación de Extranjero) und können ohne Einschränkungen kaufen, verkaufen und vermieten. DelSolPrimeHomes unterstützt internationale Käufer bei der NIE-Beantragung und allen rechtlichen Aspekten des Kaufprozesses.', 'nicht-eu-buerger-immobilien-spanien-kaufen-de', 'buying-process', ARRAY['Nicht-EU-Bürger', 'Rechtliches', 'Internationale Käufer'], ARRAY['Nicht-EU', 'Ausländer', 'Immobilienkauf', 'Rechte'], ARRAY['Können Nicht-EU-Bürger Immobilien in Spanien kaufen', 'Immobilienrechte für Ausländer Spanien'], ARRAY['Costa del Sol'], ARRAY['Alle Immobilientypen'], 'Nicht-EU-Bürger Immobilienkauf Spanien | Rechte und Verfahren', 'Alles was Nicht-EU-Bürger über den Immobilienkauf in Spanien wissen müssen. Rechte, NIE-Nummer und rechtliche Aspekte erklärt.', true, 3),

-- Legal Aspects - German
('de', 'Was ist eine NIE-Nummer und wie bekomme ich sie?', 'Die NIE ist eine Steuernummer für Ausländer, die für alle Immobilientransaktionen in Spanien erforderlich ist.', 'Die NIE (Número de Identificación de Extranjero) ist eine spanische Steuernummer für Ausländer, die für alle offiziellen Transaktionen erforderlich ist. Sie können sie beim spanischen Konsulat in Ihrem Heimatland oder direkt in Spanien bei der Policia Nacional beantragen. Benötigte Unterlagen: Reisepass, ausgefülltes Formular EX-15, Nachweis des Grundes (z.B. Immobilienkaufabsicht). DelSolPrimeHomes organisiert NIE-Termine und begleitet Sie zum Termin.', 'nie-nummer-beantragen-spanien-de', 'legal-aspects', ARRAY['NIE', 'Steuernummer', 'Beantragung'], ARRAY['NIE', 'Steuernummer', 'Ausländer', 'Beantragung'], ARRAY['Wie bekomme ich eine NIE-Nummer in Spanien', 'NIE-Nummer beantragen für Immobilienkauf'], ARRAY['Costa del Sol', 'Marbella'], ARRAY['Alle Immobilientypen'], 'NIE-Nummer beantragen Spanien | Kompletter Guide für Immobilienkäufer', 'Erfahren Sie, wie Sie eine NIE-Nummer für den Immobilienkauf in Spanien beantragen. Schritt-für-Schritt Anleitung und Dokumentenanforderungen.', true, 4),

-- Market Trends - German  
('de', 'Wie entwickeln sich die Immobilienpreise an der Costa del Sol?', 'Die Immobilienpreise an der Costa del Sol zeigen einen stabilen Aufwärtstrend mit 3-7% jährlichem Wachstum.', 'Der Immobilienmarkt an der Costa del Sol verzeichnet kontinuierliches Wachstum. Faktoren: internationale Nachfrage, begrenzte Küstenflächen, Infrastrukturinvestitionen, und Spaniens Attraktivität für Residenten. Besonders Marbella, Estepona und Benahavís zeigen starke Wertsteigerungen. DelSolPrimeHomes erstellt individuelle Marktanalysen und ROI-Prognosen für Ihre Investition.', 'immobilienpreise-costa-del-sol-entwicklung-de', 'market-trends', ARRAY['Markttrends', 'Preise', 'Investment'], ARRAY['Preise', 'Markt', 'Trends', 'Costa del Sol'], ARRAY['Wie entwickeln sich die Immobilienpreise Costa del Sol', 'Immobilienmarkt Costa del Sol Prognose'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['Villa', 'Apartment', 'Penthouse'], 'Immobilienpreise Costa del Sol | Markttrends und Prognosen 2024', 'Aktuelle Entwicklung der Immobilienpreise an der Costa del Sol. Marktanalyse, Trends und Investmentprognosen für 2024 und darüber hinaus.', true, 5),

-- Financing - German
('de', 'Kann ich als Ausländer eine Hypothek in Spanien bekommen?', 'Ja, spanische Banken bieten Ausländern Hypotheken bis zu 70% des Immobilienwerts an.', 'Ausländer können spanische Hypotheken beantragen. Banken finanzieren bis zu 70% für Nicht-Residenten und bis zu 80% für Residenten. Anforderungen: Einkommensnachweis, Kreditauskunft, NIE-Nummer, Anzahlung (mindestens 30%). Zinssätze variieren je nach Profil. DelSolPrimeHomes arbeitet mit führenden spanischen Banken zusammen und unterstützt bei der Hypothekantragsstellung.', 'hypothek-spanien-auslaender-de', 'financing', ARRAY['Hypothek', 'Finanzierung', 'Ausländer'], ARRAY['Hypothek', 'Finanzierung', 'Bank', 'Ausländer'], ARRAY['Kann ich als Ausländer eine Hypothek in Spanien bekommen', 'Immobilienfinanzierung Spanien Ausländer'], ARRAY['Costa del Sol'], ARRAY['Alle Immobilientypen'], 'Hypothek Spanien für Ausländer | Finanzierungsmöglichkeiten und Konditionen', 'Alles über Hypotheken in Spanien für ausländische Käufer. Konditionen, Anforderungen und Finanzierungsmöglichkeiten im Detail.', true, 6),

-- Property Types - German
('de', 'Was ist der Unterschied zwischen einer Villa und einem Townhouse?', 'Villen sind freistehende Häuser mit eigenem Grundstück, Townhouses sind Reihenhäuser in Wohnanlagen.', 'Villen bieten maximale Privatsphäre als freistehende Immobilien mit eigenem Grundstück, Garten und oft privatem Pool. Townhouses sind elegante Reihenhäuser in geschlossenen Wohnanlagen mit gemeinschaftlichen Einrichtungen wie Pool, Gärten und Sicherheitsdienst. Beide Optionen haben Vor- und Nachteile je nach Lebensstil, Budget und Präferenzen. DelSolPrimeHomes hilft bei der optimalen Auswahl basierend auf Ihren individuellen Bedürfnissen.', 'unterschied-villa-townhouse-spanien-de', 'property-types', ARRAY['Villa', 'Townhouse', 'Immobilientypen'], ARRAY['Villa', 'Townhouse', 'Unterschied', 'Immobilientypen'], ARRAY['Was ist der Unterschied zwischen Villa und Townhouse', 'Villa oder Townhouse kaufen Spanien'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['Villa', 'Townhouse'], 'Villa vs Townhouse Spanien | Unterschiede und Vor-/Nachteile erklärt', 'Detaillierter Vergleich zwischen Villen und Townhouses in Spanien. Entscheidungshilfe für den optimalen Immobilientyp an der Costa del Sol.', false, 7),

-- Locations - German  
('de', 'Warum ist Marbella so beliebt bei internationalen Käufern?', 'Marbella kombiniert Luxus, Klima, Infrastruktur und internationale Gemeinschaft perfekt.', 'Marbella ist das Premium-Ziel der Costa del Sol durch: exklusives Ambiente, weltklasse Golfplätze, Michelin-Restaurants, Puerto Banús Marina, internationale Schulen, erstklassige Gesundheitsversorgung, und eine etablierte internationale Gemeinschaft. Die Goldene Meile bietet einige der luxuriösesten Immobilien Europas. DelSolPrimeHomes spezialisiert sich auf exklusive Marbella-Properties.', 'warum-marbella-beliebt-internationale-kaeufer-de', 'locations', ARRAY['Marbella', 'Beliebtheit', 'International'], ARRAY['Marbella', 'Luxus', 'international', 'Käufer'], ARRAY['Warum ist Marbella so beliebt', 'Marbella für internationale Käufer'], ARRAY['Marbella', 'Puerto Banús', 'Golden Mile'], ARRAY['Villa', 'Penthouse', 'Apartment'], 'Warum Marbella? | Vorteile für internationale Immobilienkäufer', 'Entdecken Sie, warum Marbella das Top-Ziel für internationale Immobilienkäufer ist. Luxus, Lifestyle und Investmentpotenzial an der Costa del Sol.', true, 8),

-- Investment - German
('de', 'Welche Rendite kann ich mit Mietimmobilien an der Costa del Sol erwarten?', 'Mietrenditen an der Costa del Sol liegen zwischen 4-8% je nach Lage und Immobilientyp.', 'Mietrenditen variieren stark nach Standort und Immobilientyp: Ferienvermietung 6-8% (Marbella, Puerto Banús), Langzeitmiete 4-6% (Estepona, Fuengirola), Luxusimmobilien 3-5% (aber höhere Wertsteigerung). Faktoren: Tourismus, Lage, Ausstattung, Verwaltung. DelSolPrimeHomes erstellt detaillierte ROI-Analysen und übernimmt Vermietungsmanagement für optimale Renditen.', 'mietrendite-costa-del-sol-erwarten-de', 'investment', ARRAY['Rendite', 'Vermietung', 'ROI'], ARRAY['Rendite', 'Miete', 'Investment', 'ROI'], ARRAY['Welche Mietrendite Costa del Sol', 'ROI Immobilien Costa del Sol'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['Villa', 'Apartment', 'Penthouse'], 'Mietrenditen Costa del Sol | ROI-Guide für Immobilieninvestoren', 'Detaillierte Analyse der Mietrenditen an der Costa del Sol. ROI-Potenzial, Renditeerwartungen und Investmentstrategien für maximale Erträge.', true, 9),

-- Services - German
('de', 'Bieten Sie Unterstützung bei der Einrichtung von Versorgungsunternehmen an?', 'Ja, DelSolPrimeHomes koordiniert alle Versorgungsanschlüsse und Behördengänge für neue Eigentümer.', 'Unser vollständiger Service umfasst: Strom- und Wasseranmeldung, Internet- und TV-Installation, Gemeindesteuer-Registrierung, Abfallentsorgung-Anmeldung, Versicherungsberatung, und Bankkonten-Eröffnung. Wir arbeiten mit vertrauenswürdigen lokalen Anbietern zusammen und stellen sicher, dass Ihre neue Immobilie bezugsfertig ist. Unser Concierge-Service macht den Übergang nahtlos und stressfrei.', 'versorgungsunternehmen-einrichtung-service-de', 'services', ARRAY['Versorgung', 'Service', 'Einrichtung'], ARRAY['Versorgung', 'Strom', 'Wasser', 'Service'], ARRAY['Hilfe bei Versorgungsanmeldung Spanien', 'Service für neue Immobilieneigentümer'], ARRAY['Costa del Sol'], ARRAY['Alle Immobilientypen'], 'Versorgungsanmeldung Spanien | Kompletter Service für neue Eigentümer', 'DelSolPrimeHomes übernimmt alle Versorgungsanmeldungen und Behördengänge. Strom, Wasser, Internet - alles aus einer Hand organisiert.', false, 10),

-- Technology - German
('de', 'Wie funktioniert Ihre virtuelle Besichtigungstechnologie?', 'Unsere VR-Technologie ermöglicht realistische 360°-Immobilienbesichtigungen von überall aus.', 'Unsere fortschrittliche VR-Technologie bietet: hochauflösende 360°-Aufnahmen, interaktive Grundrisse, detaillierte Raumvermessungen, virtuelle Möblierung, und Live-Video-Calls mit unseren Experten während der Besichtigung. Sie können Immobilien realistisch erleben, bevor Sie nach Spanien reisen. Die Technologie ist über Computer, Tablet oder VR-Headset zugänglich und spart Zeit und Reisekosten.', 'virtuelle-besichtigung-technologie-vr-de', 'technology', ARRAY['VR', 'Virtuelle Besichtigung', 'Technologie'], ARRAY['VR', 'virtuell', 'Besichtigung', 'Technologie'], ARRAY['Wie funktioniert virtuelle Immobilienbesichtigung', 'VR Technologie Immobilien'], ARRAY['Costa del Sol'], ARRAY['Alle Immobilientypen'], 'Virtuelle Immobilienbesichtigung | VR-Technologie für Fernkäufer', 'Revolutionäre VR-Technologie für realistische Immobilienbesichtigungen. 360°-Touren und virtuelle Besichtigungen von überall aus.', false, 11),

-- Polish FAQ Translations (pl)
('pl', 'Ile czasu trwa proces zakupu nieruchomości w Hiszpanii?', 'Proces zakupu nieruchomości w Hiszpanii zazwyczaj trwa 8-12 tygodni od zaakceptowania oferty.', 'Kompletny proces zakupu nieruchomości w Hiszpanii obejmuje kilka etapów: akceptacja oferty (1-2 tygodnie), umowa rezerwacyjna i zaliczka (1 tydzień), due diligence i kontrola prawna (3-4 tygodnie), przetwarzanie wniosku kredytowego jeśli potrzebne (4-6 tygodni), i finalne podpisanie u notariusza (1-2 tygodnie). DelSolPrimeHomes przeprowadzi Cię przez każdy krok.', 'ile-czasu-proces-zakup-nieruchomosci-hiszpania-pl', 'buying-process', ARRAY['Czas trwania', 'Proces zakupu', 'Hiszpania'], ARRAY['Zakup nieruchomości', 'Czas', 'Hiszpania', 'Proces'], ARRAY['Ile czasu trwa zakup nieruchomości w Hiszpanii', 'Czas procesu zakupu nieruchomości Hiszpania'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['Villa', 'Apartament', 'Townhouse'], 'Zakup Nieruchomości Hiszpania: Czas i Proces | DelSolPrimeHomes', 'Dowiedz się, ile czasu trwa proces zakupu nieruchomości w Hiszpanii. Kompletny przewodnik z harmonogramem dla każdego kroku procesu.', false, 1),

('pl', 'Jakie podatki obowiązują przy zakupie nieruchomości w Hiszpanii?', 'Główne podatki to ITP (6-10%), opłaty notarialne i rejestracyjne (1-2%) oraz ewentualne podatki hipoteczne.', 'Przy zakupie nieruchomości w Hiszpanii obowiązują różne podatki i opłaty: podatek od przeniesienia własności (ITP) 6-10% w zależności od wspólnoty autonomicznej, opłaty notarialne i księgi wieczystej (1-2% ceny zakupu), koszty prawne (1-1.5%), podatki hipoteczne jeśli dotyczy (0.5-1%), i ewentualny VAT (10%) przy nowych budowach. DelSolPrimeHomes przygotowuje transparentne wyceny kosztów.', 'jakie-podatki-zakup-nieruchomosci-hiszpania-pl', 'buying-process', ARRAY['Podatki', 'Koszty', 'Zakup nieruchomości'], ARRAY['Podatki', 'ITP', 'Podatek transferowy', 'Koszty'], ARRAY['Jakie podatki przy zakupie nieruchomości w Hiszpanii', 'Koszty zakupu nieruchomości Hiszpania'], ARRAY['Costa del Sol', 'Andaluzja'], ARRAY['Wszystkie typy nieruchomości'], 'Podatki przy Zakupie Nieruchomości w Hiszpanii | Kompletny Przewodnik', 'Pełny przegląd wszystkich podatków i opłat przy zakupie nieruchomości w Hiszpanii. ITP, opłaty notarialne i inne koszty wyjaśnione.', true, 2),

('pl', 'Czy mogę kupić nieruchomość w Hiszpanii jako obywatel spoza UE?', 'Tak, obywatele spoza UE mogą swobodnie kupować nieruchomości w Hiszpanii z takimi samymi prawami jak obywatele UE.', 'Obywatele spoza UE mają takie same prawa do zakupu nieruchomości w Hiszpanii jak obywatele UE. Potrzebują tylko numeru NIE (Número de Identificación de Extranjero) i mogą bez ograniczeń kupować, sprzedawać i wynajmować. DelSolPrimeHomes pomaga międzynarodowym kupującym w uzyskaniu NIE i wszystkich aspektach prawnych procesu zakupu.', 'obywatel-spoza-ue-kupno-nieruchomosci-hiszpania-pl', 'buying-process', ARRAY['Obywatele spoza UE', 'Prawne', 'Międzynarodowi kupujący'], ARRAY['Spoza UE', 'Cudzoziemcy', 'Zakup nieruchomości', 'Prawa'], ARRAY['Czy obywatele spoza UE mogą kupić nieruchomość w Hiszpanii', 'Prawa nieruchomości dla cudzoziemców Hiszpania'], ARRAY['Costa del Sol'], ARRAY['Wszystkie typy nieruchomości'], 'Zakup Nieruchomości Hiszpania dla Obywateli spoza UE | Prawa i Procedury', 'Wszystko co obywatele spoza UE muszą wiedzieć o zakupie nieruchomości w Hiszpanii. Prawa, numer NIE i aspekty prawne wyjaśnione.', true, 3),

-- Danish FAQ Translations (dk)
('dk', 'Hvor lang tid tager ejendomskøbsprocessen i Spanien?', 'Ejendomskøbsprocessen i Spanien tager normalt 8-12 uger fra tilbudets accept.', 'Den komplette ejendomskøbsprocess i Spanien omfatter flere faser: tilbudsaccept (1-2 uger), reservationskontrakt og depositum (1 uge), due diligence og juridisk kontrol (3-4 uger), behandling af låneansøgning hvis nødvendigt (4-6 uger), og endelig notariel underskrivelse (1-2 uger). DelSolPrimeHomes guider dig gennem hvert trin.', 'hvor-lang-tid-ejendomskob-proces-spanien-dk', 'buying-process', ARRAY['Tidsramme', 'Købsprocess', 'Spanien'], ARRAY['Ejendomskøb', 'Tidsramme', 'Spanien', 'Process'], ARRAY['Hvor lang tid tager det at købe ejendom i Spanien', 'Tidsramme for ejendomskøb Spanien'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['Villa', 'Lejlighed', 'Townhouse'], 'Ejendomskøb Spanien: Tidsramme og Process | DelSolPrimeHomes', 'Lær, hvor lang tid ejendomskøbsprocessen i Spanien tager. Komplet guide med tidsramme for hvert trin af købsprocessen.', false, 1),

('dk', 'Hvilke skatter gælder ved ejendomskøb i Spanien?', 'Hovedskatterne er ITP (6-10%), notar- og registreringsgebyrer (1-2%) samt eventuelle realkreditskatter.', 'Ved ejendomskøb i Spanien gælder forskellige skatter og gebyrer: ejendomsoverdragelsesskat (ITP) 6-10% afhængigt af den selvstyrende region, notar- og tinglysningsgebyrer (1-2% af købsprisen), advokatomkostninger (1-1.5%), realkreditskatter hvis relevant (0.5-1%), og eventuel moms (10%) ved nybyggeri. DelSolPrimeHomes udarbejder transparente omkostningsestimater.', 'hvilke-skatter-ejendomskob-spanien-dk', 'buying-process', ARRAY['Skatter', 'Omkostninger', 'Ejendomskøb'], ARRAY['Skatter', 'ITP', 'Overdragelsesskat', 'Omkostninger'], ARRAY['Hvilke skatter skal jeg betale ved ejendomskøb i Spanien', 'Omkostninger for ejendomskøb Spanien'], ARRAY['Costa del Sol', 'Andalusien'], ARRAY['Alle ejendomstyper'], 'Skatter ved Ejendomskøb i Spanien | Komplet Guide', 'Komplet oversigt over alle skatter og gebyrer ved ejendomskøb i Spanien. ITP, notargebyrer og andre omkostninger forklaret.', true, 2),

('dk', 'Kan jeg købe ejendom i Spanien som ikke-EU-borger?', 'Ja, ikke-EU-borgere kan frit købe ejendom i Spanien med samme rettigheder som EU-borgere.', 'Ikke-EU-borgere har samme ejendomsrettigheder i Spanien som EU-borgere. De skal blot have et NIE-nummer (Número de Identificación de Extranjero) og kan købe, sælge og udleje uden begrænsninger. DelSolPrimeHomes hjælper internationale købere med NIE-ansøgning og alle juridiske aspekter af købsprocessen.', 'ikke-eu-borger-kobe-ejendom-spanien-dk', 'buying-process', ARRAY['Ikke-EU-borgere', 'Juridisk', 'Internationale købere'], ARRAY['Ikke-EU', 'Udlændinge', 'Ejendomskøb', 'Rettigheder'], ARRAY['Kan ikke-EU-borgere købe ejendom i Spanien', 'Ejendomsrettigheder for udlændinge Spanien'], ARRAY['Costa del Sol'], ARRAY['Alle ejendomstyper'], 'Ikke-EU-Borgere Ejendomskøb Spanien | Rettigheder og Procedurer', 'Alt hvad ikke-EU-borgere skal vide om ejendomskøb i Spanien. Rettigheder, NIE-nummer og juridiske aspekter forklaret.', true, 3),

-- Swedish FAQ Translations (se)  
('se', 'Hur lång tid tar fastighetsköpsprocessen i Spanien?', 'Fastighetsköpsprocessen i Spanien tar normalt 8-12 veckor från budacceptans.', 'Den kompletta fastighetsköpsprocessen i Spanien omfattar flera faser: budacceptans (1-2 veckor), reservationskontrakt och handpenning (1 vecka), due diligence och juridisk kontroll (3-4 veckor), behandling av låneansökan om nödvändigt (4-6 veckor), och slutlig notariell underteckning (1-2 veckor). DelSolPrimeHomes guidar dig genom varje steg.', 'hur-lang-tid-fastighetskop-process-spanien-se', 'buying-process', ARRAY['Tidsram', 'Köpprocess', 'Spanien'], ARRAY['Fastighetsköp', 'Tidsram', 'Spanien', 'Process'], ARRAY['Hur lång tid tar det att köpa fastighet i Spanien', 'Tidsram för fastighetsköp Spanien'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['Villa', 'Lägenhet', 'Townhouse'], 'Fastighetsköp Spanien: Tidsram och Process | DelSolPrimeHomes', 'Lär dig hur lång tid fastighetsköpsprocessen i Spanien tar. Komplett guide med tidsram för varje steg av köpprocessen.', false, 1),

('se', 'Vilka skatter gäller vid fastighetsköp i Spanien?', 'Huvudskatterna är ITP (6-10%), notar- och registreringsavgifter (1-2%) samt eventuella bolåneskatter.', 'Vid fastighetsköp i Spanien gäller olika skatter och avgifter: fastighetsöverlåtelseskatt (ITP) 6-10% beroende på den autonoma regionen, notar- och inskrivningsavgifter (1-2% av köpesumman), advokatskostnader (1-1.5%), bolåneskatter om tillämpligt (0.5-1%), och eventuell moms (10%) vid nyproduktion. DelSolPrimeHomes upprättar transparenta kostnadsestimationer.', 'vilka-skatter-fastighetskop-spanien-se', 'buying-process', ARRAY['Skatter', 'Kostnader', 'Fastighetsköp'], ARRAY['Skatter', 'ITP', 'Överlåtelseskatt', 'Kostnader'], ARRAY['Vilka skatter ska jag betala vid fastighetsköp i Spanien', 'Kostnader för fastighetsköp Spanien'], ARRAY['Costa del Sol', 'Andalusien'], ARRAY['Alla fastighetstyper'], 'Skatter vid Fastighetsköp i Spanien | Komplett Guide', 'Komplett översikt över alla skatter och avgifter vid fastighetsköp i Spanien. ITP, notaravgifter och andra kostnader förklarade.', true, 2),

('se', 'Kan jag köpa fastighet i Spanien som icke-EU-medborgare?', 'Ja, icke-EU-medborgare kan fritt köpa fastighet i Spanien med samma rättigheter som EU-medborgare.', 'Icke-EU-medborgare har samma fastighetsrättigheter i Spanien som EU-medborgare. De behöver bara ett NIE-nummer (Número de Identificación de Extranjero) och kan köpa, sälja och hyra ut utan begränsningar. DelSolPrimeHomes hjälper internationella köpare med NIE-ansökan och alla juridiska aspekter av köpprocessen.', 'icke-eu-medborgare-kopa-fastighet-spanien-se', 'buying-process', ARRAY['Icke-EU-medborgare', 'Juridiskt', 'Internationella köpare'], ARRAY['Icke-EU', 'Utlänningar', 'Fastighetsköp', 'Rättigheter'], ARRAY['Kan icke-EU-medborgare köpa fastighet i Spanien', 'Fastighetsrättigheter för utlänningar Spanien'], ARRAY['Costa del Sol'], ARRAY['Alla fastighetstyper'], 'Icke-EU-Medborgare Fastighetsköp Spanien | Rättigheter och Procedurer', 'Allt som icke-EU-medborgare behöver veta om fastighetsköp i Spanien. Rättigheter, NIE-nummer och juridiska aspekter förklarade.', true, 3);

-- FAQ Categories for all languages
INSERT INTO public.faq_categories (key, language, name, description, icon, sort_order) VALUES
-- German Categories
('buying-process', 'de', 'Kaufprozess', 'Alles über den Immobilienkaufprozess in Spanien', 'Home', 1),
('legal-aspects', 'de', 'Rechtliche Aspekte', 'Rechtliche Informationen und Anforderungen', 'Scale', 2),
('market-trends', 'de', 'Markttrends', 'Aktuelle Marktentwicklungen und Prognosen', 'TrendingUp', 3),
('financing', 'de', 'Finanzierung', 'Hypotheken und Finanzierungsoptionen', 'CreditCard', 4),
('property-types', 'de', 'Immobilientypen', 'Verschiedene Arten von Immobilien', 'Building', 5),
('locations', 'de', 'Standorte', 'Beliebte Gebiete an der Costa del Sol', 'MapPin', 6),
('investment', 'de', 'Investment', 'Investmentstrategien und ROI-Informationen', 'PiggyBank', 7),
('services', 'de', 'Dienstleistungen', 'Unsere Services und Unterstützung', 'Users', 8),
('technology', 'de', 'Technologie', 'Innovative Technologien und Tools', 'Smartphone', 9),
('lifestyle', 'de', 'Lifestyle', 'Leben an der Costa del Sol', 'Sun', 10),

-- Polish Categories  
('buying-process', 'pl', 'Proces Zakupu', 'Wszystko o procesie zakupu nieruchomości w Hiszpanii', 'Home', 1),
('legal-aspects', 'pl', 'Aspekty Prawne', 'Informacje prawne i wymagania', 'Scale', 2),
('market-trends', 'pl', 'Trendy Rynkowe', 'Aktualne trendy rynkowe i prognozy', 'TrendingUp', 3),
('financing', 'pl', 'Finansowanie', 'Kredyty hipoteczne i opcje finansowania', 'CreditCard', 4),
('property-types', 'pl', 'Typy Nieruchomości', 'Różne rodzaje nieruchomości', 'Building', 5),
('locations', 'pl', 'Lokalizacje', 'Popularne obszary na Costa del Sol', 'MapPin', 6),
('investment', 'pl', 'Inwestycje', 'Strategie inwestycyjne i informacje ROI', 'PiggyBank', 7),
('services', 'pl', 'Usługi', 'Nasze usługi i wsparcie', 'Users', 8),
('technology', 'pl', 'Technologia', 'Innowacyjne technologie i narzędzia', 'Smartphone', 9),
('lifestyle', 'pl', 'Styl Życia', 'Życie na Costa del Sol', 'Sun', 10),

-- Danish Categories
('buying-process', 'dk', 'Købsprocess', 'Alt om ejendomskøbsprocessen i Spanien', 'Home', 1),
('legal-aspects', 'dk', 'Juridiske Aspekter', 'Juridisk information og krav', 'Scale', 2),
('market-trends', 'dk', 'Markedstendenser', 'Aktuelle markedsudviklinger og prognoser', 'TrendingUp', 3),
('financing', 'dk', 'Finansiering', 'Realkreditlån og finansieringsmuligheder', 'CreditCard', 4),
('property-types', 'dk', 'Ejendomstyper', 'Forskellige typer af ejendomme', 'Building', 5),
('locations', 'dk', 'Lokationer', 'Populære områder på Costa del Sol', 'MapPin', 6),
('investment', 'dk', 'Investering', 'Investeringsstrategier og ROI-information', 'PiggyBank', 7),
('services', 'dk', 'Tjenester', 'Vores services og support', 'Users', 8),
('technology', 'dk', 'Teknologi', 'Innovative teknologier og værktøjer', 'Smartphone', 9),
('lifestyle', 'dk', 'Livsstil', 'Livet på Costa del Sol', 'Sun', 10),

-- Swedish Categories
('buying-process', 'se', 'Köpprocess', 'Allt om fastighetsköpsprocessen i Spanien', 'Home', 1),
('legal-aspects', 'se', 'Juridiska Aspekter', 'Juridisk information och krav', 'Scale', 2),
('market-trends', 'se', 'Marknadstrender', 'Aktuella marknadsutvecklingar och prognoser', 'TrendingUp', 3),
('financing', 'se', 'Finansiering', 'Bolån och finansieringsalternativ', 'CreditCard', 4),
('property-types', 'se', 'Fastighetstyper', 'Olika typer av fastigheter', 'Building', 5),
('locations', 'se', 'Platser', 'Populära områden på Costa del Sol', 'MapPin', 6),
('investment', 'se', 'Investering', 'Investeringsstrategier och ROI-information', 'PiggyBank', 7),
('services', 'se', 'Tjänster', 'Våra tjänster och support', 'Users', 8),
('technology', 'se', 'Teknik', 'Innovativa teknologier och verktyg', 'Smartphone', 9),
('lifestyle', 'se', 'Livsstil', 'Livet på Costa del Sol', 'Sun', 10);