-- Insert comprehensive FAQ content for Costa del Sol real estate

-- Insert FAQ categories first
INSERT INTO faq_categories (key, language, name, description, icon, sort_order) VALUES
('buying', 'en', 'Buying Property', 'Everything about purchasing property in Costa del Sol', 'Home', 1),
('selling', 'en', 'Selling Property', 'Guide to selling your Costa del Sol property', 'TrendingUp', 2),
('viewing', 'en', 'Viewing Trips', 'Planning and organizing property viewing trips', 'MapPin', 3),
('finance', 'en', 'Finance & Taxes', 'Financial aspects and Spanish tax obligations', 'Calculator', 4),
('legal', 'en', 'Legal & Notary', 'Legal processes and notary requirements', 'Scale', 5),
('residency', 'en', 'Residency & Visas', 'Visa requirements and residency applications', 'Globe', 6),
('lifestyle', 'en', 'Lifestyle & Culture', 'Living in Costa del Sol and local culture', 'Heart', 7),
('property-types', 'en', 'Property Types', 'Different types of properties available', 'Building', 8),
('timeline', 'en', 'Timeline & Process', 'Purchase timeline and key milestones', 'Clock', 9),
('technology', 'en', 'AI Assistant & Technology', 'About Isabelle and our platform features', 'Bot', 10)
ON CONFLICT (key, language) DO NOTHING;

-- Insert comprehensive FAQs
INSERT INTO faqs (language, question, answer_short, answer_long, slug, category, tags, location, is_featured, sort_order, meta_title, meta_description, keywords, voice_queries, target_areas, property_types) VALUES

-- Buying Property FAQs (15 questions)
('en', 'What are the costs involved in buying property in Spain?', 'Expect 10-15% of property value in additional costs including taxes, legal fees, and notary charges.', 'When buying property in Spain, budget for 10-15% of the purchase price in additional costs. These include: Transfer Tax (ITP) of 8-10% for resale properties or VAT (IVA) of 10% for new builds, plus Stamp Duty (AJD) of 1-1.5%. Legal fees typically cost 1-2% of purchase price, notary fees around €600-1,200, Land Registry fees €400-800, and property survey €300-600. Don''t forget ongoing costs like annual property tax (IBI), community fees for apartments, and utility connections.', 'costs-buying-property-spain', 'buying', ARRAY['costs', 'taxes', 'fees', 'budget'], 'Costa del Sol', true, 1, 'Property Buying Costs in Spain - Complete Guide', 'Complete breakdown of all costs when buying property in Spain including taxes, legal fees, and hidden expenses.', ARRAY['buying costs spain', 'property taxes spain', 'legal fees'], ARRAY['what does it cost to buy property in spain', 'how much are buying costs in spain'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['villa', 'apartment', 'townhouse']),

('en', 'Do I need a Spanish bank account to buy property?', 'While not legally required, having a Spanish bank account makes the process much easier and is often required by banks for mortgages.', 'While you can technically buy Spanish property without a Spanish bank account, it''s highly recommended to open one. Spanish banks require a local account for mortgage applications, and it simplifies the purchase process, utility payments, and ongoing property management. You''ll need your NIE number and proof of income to open an account. Many international banks have Spanish branches that can facilitate the process for existing customers.', 'spanish-bank-account-property', 'buying', ARRAY['bank account', 'NIE', 'mortgage', 'requirements'], 'Costa del Sol', true, 2, 'Do You Need a Spanish Bank Account for Property Purchase?', 'Learn why opening a Spanish bank account is essential for buying property and how to set one up.', ARRAY['spanish bank account', 'NIE number', 'property purchase'], ARRAY['do i need spanish bank account for property'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment']),

('en', 'What is an NIE number and how do I get one?', 'An NIE (Número de Identificación de Extranjero) is a tax identification number required for all property transactions in Spain.', 'The NIE (Número de Identificación de Extranjero) is essential for any foreigner engaging in economic activities in Spain, including buying property. You can apply at Spanish consulates in your home country, Spanish police stations, or through a legal representative (gestor). Required documents include completed EX-15 form, passport copy, proof of need (property reservation contract), and fee payment (around €12). Processing takes 1-4 weeks depending on location. The NIE is valid for life and required for property purchases, bank accounts, utility contracts, and tax obligations.', 'nie-number-spain-how-to-get', 'buying', ARRAY['NIE', 'identification', 'requirements', 'documents'], 'Costa del Sol', true, 3, 'NIE Number Spain: Complete Application Guide', 'Step-by-step guide to obtaining your NIE number for Spanish property purchase and other transactions.', ARRAY['NIE number spain', 'spanish tax number', 'foreigner identification'], ARRAY['what is NIE number', 'how to get NIE number spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment', 'townhouse']),

('en', 'Can non-residents get a mortgage in Spain?', 'Yes, non-residents can obtain Spanish mortgages, typically up to 70% of property value with higher interest rates than residents.', 'Non-residents can secure Spanish mortgages, but conditions differ from resident mortgages. Banks typically offer up to 70% loan-to-value (compared to 80% for residents), require higher deposits, and charge higher interest rates (usually 1-2% more). You''ll need proof of income (last 3 years'' tax returns), bank statements, employment contract, and NIE number. The property serves as collateral, and you''ll need Spanish life insurance. Popular lenders include Banco Sabadell, BBVA, and CaixaBank. Consider using a mortgage broker to compare options and navigate the application process.', 'non-resident-mortgage-spain', 'buying', ARRAY['mortgage', 'non-resident', 'financing', 'banks'], 'Costa del Sol', true, 4, 'Non-Resident Mortgages in Spain: Complete Guide', 'Everything non-residents need to know about getting a Spanish mortgage including requirements and best lenders.', ARRAY['non resident mortgage spain', 'spanish mortgage foreigners', 'property financing'], ARRAY['can foreigners get mortgage in spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment']),

('en', 'What should I look for in a Spanish property lawyer?', 'Choose a lawyer who speaks your language, specializes in property law, is registered with local bar association, and has experience with international clients.', 'Selecting the right Spanish property lawyer is crucial for a smooth purchase. Look for: fluency in your language, specialization in real estate law, registration with the local Colegio de Abogados (bar association), experience with international clients, transparent fee structure (typically 1-2% of purchase price), and positive client references. They should handle due diligence, contract review, title deed verification, tax obligations, and represent you at the notary signing. Avoid lawyers recommended solely by estate agents or developers to ensure independence.', 'choosing-spanish-property-lawyer', 'buying', ARRAY['lawyer', 'legal', 'due diligence', 'representation'], 'Costa del Sol', false, 5, 'How to Choose the Right Spanish Property Lawyer', 'Essential criteria for selecting a qualified property lawyer in Spain for your real estate purchase.', ARRAY['spanish property lawyer', 'real estate attorney spain', 'legal representation'], ARRAY['how to choose property lawyer spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment', 'townhouse']),

('en', 'What is the property buying process timeline in Spain?', 'The typical Spanish property purchase takes 6-12 weeks from offer acceptance to completion, depending on mortgage requirements and legal checks.', 'Spanish property purchase timeline: Week 1-2: Submit offer, negotiate terms, sign reservation contract (10% deposit). Week 2-4: Apply for NIE number and mortgage (if needed), lawyer conducts due diligence. Week 4-6: Mortgage approval, sign private purchase contract (arras), pay additional 10-20% deposit. Week 6-12: Complete mortgage paperwork, final legal checks, building surveys. Final week: Transfer remaining funds, attend notary signing (escritura), receive property keys. Cash purchases can complete faster (4-6 weeks), while mortgage purchases may take longer due to bank processing times.', 'spanish-property-buying-timeline', 'buying', ARRAY['timeline', 'process', 'stages', 'completion'], 'Costa del Sol', true, 6, 'Spanish Property Buying Process: Complete Timeline', 'Step-by-step timeline of the Spanish property purchase process from offer to completion.', ARRAY['property buying timeline spain', 'purchase process spain', 'buying stages'], ARRAY['how long to buy property spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment', 'townhouse']),

('en', 'What is the difference between reservation and purchase contracts?', 'Reservation contracts secure the property with a small deposit, while purchase contracts are legally binding agreements requiring larger deposits.', 'In Spanish property transactions, there are typically two contracts: 1) Reservation Contract (Contrato de Reserva): Initial agreement securing the property, usually requiring 1-6,000€ deposit. Gives time for legal checks and mortgage applications. Generally refundable if major issues found. 2) Purchase Contract (Contrato de Arras): Legally binding agreement typically requiring 10-20% deposit. Sets completion date, terms, and penalties for withdrawal. If buyer withdraws, they lose the deposit; if seller withdraws, they must return double the deposit. This leads to the final Escritura (title deed) signing at the notary.', 'reservation-vs-purchase-contracts', 'buying', ARRAY['contracts', 'reservation', 'arras', 'deposits'], 'Costa del Sol', false, 7, 'Spanish Property Contracts: Reservation vs Purchase', 'Understanding the difference between reservation and purchase contracts in Spanish real estate.', ARRAY['spanish property contracts', 'reservation contract', 'purchase contract'], ARRAY['difference between property contracts spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment']),

('en', 'Are there restrictions on foreign property ownership in Spain?', 'No, there are generally no restrictions on foreign property ownership in Spain, with full rights equal to Spanish citizens.', 'Spain welcomes foreign property investment with no restrictions on non-resident ownership. Foreign buyers have the same property rights as Spanish citizens, including the right to buy, sell, rent, and inherit property. You can own multiple properties and there are no limits on the value or number of properties purchased. The only requirements are obtaining an NIE number for the transaction and complying with tax obligations. EU citizens have slightly simpler procedures, while non-EU citizens may need additional documentation but face no ownership restrictions.', 'foreign-property-ownership-restrictions', 'buying', ARRAY['foreign ownership', 'restrictions', 'rights', 'regulations'], 'Costa del Sol', false, 8, 'Foreign Property Ownership in Spain: Rights and Restrictions', 'Complete guide to foreign property ownership rights and regulations in Spain.', ARRAY['foreign property ownership spain', 'buy property spain foreigner', 'ownership rights'], ARRAY['can foreigners buy property spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment', 'townhouse']),

('en', 'What surveys should I get before buying?', 'Get a structural survey for older properties, swimming pool inspection, and pest inspection. New builds should have 10-year insurance.', 'Essential surveys for Spanish property: 1) Structural Survey: Recommended for properties over 20 years, checks foundation, walls, roof, plumbing, electricity (€300-600). 2) Swimming Pool Survey: For properties with pools, checks equipment, structure, compliance (€200-400). 3) Pest Inspection: Particularly important in coastal areas for termites and woodworm (€150-300). 4) New Build Inspection: For off-plan purchases, check build quality and compliance with plans. 5) Energy Certificate: Mandatory document showing energy efficiency rating. Your lawyer should also verify legal compliance, planning permissions, and outstanding debts.', 'property-surveys-before-buying', 'buying', ARRAY['surveys', 'inspections', 'structural', 'safety'], 'Costa del Sol', false, 9, 'Essential Property Surveys Before Buying in Spain', 'Guide to property surveys and inspections needed before purchasing Spanish real estate.', ARRAY['property survey spain', 'building inspection', 'structural survey'], ARRAY['what surveys needed buying property spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment', 'townhouse']),

('en', 'How do community fees work in Spanish apartments?', 'Community fees cover shared building costs like maintenance, cleaning, security, and utilities for common areas.', 'Spanish apartment community fees (gastos de comunidad) are mandatory monthly charges covering: building maintenance, communal area cleaning, elevator servicing, security systems, gardening, swimming pool maintenance, insurance for common areas, and utilities for shared spaces. Fees vary from €50-500+ monthly depending on building amenities and location. These are separate from your mortgage, taxes, and utilities. The community holds annual meetings where owners vote on budgets and major decisions. Always check current and any outstanding community debts before purchase, as new owners can inherit previous debts.', 'community-fees-spanish-apartments', 'buying', ARRAY['community fees', 'apartments', 'maintenance', 'costs'], 'Costa del Sol', false, 10, 'Spanish Apartment Community Fees: Complete Guide', 'Everything about community fees for Spanish apartments including costs and what they cover.', ARRAY['community fees spain', 'apartment charges spain', 'gastos comunidad'], ARRAY['what are community fees spanish apartments'], ARRAY['Costa del Sol'], ARRAY['apartment']),

-- Selling Property FAQs (10 questions)
('en', 'How much commission do Spanish estate agents charge?', 'Spanish estate agents typically charge 3-6% commission plus VAT, usually paid by the seller.', 'Spanish estate agent commission rates typically range from 3-6% of the sale price plus 21% VAT, making the total 3.6-7.3%. This is usually paid by the seller, though some agents may negotiate shared commissions. Premium areas like Marbella may have higher rates (5-6%), while rural areas might be lower (3-4%). Commission is only payable upon successful completion. Always clarify the exact percentage, what services are included, marketing scope, and exclusivity terms before signing any agency agreement.', 'spanish-estate-agent-commission', 'selling', ARRAY['commission', 'estate agent', 'selling costs', 'fees'], 'Costa del Sol', true, 1, 'Spanish Estate Agent Commission Rates and Fees', 'Guide to estate agent commission rates when selling property in Spain.', ARRAY['estate agent commission spain', 'property selling costs', 'agent fees'], ARRAY['how much do estate agents charge spain'], ARRAY['Costa del Sol', 'Marbella'], ARRAY['villa', 'apartment']),

('en', 'What taxes do I pay when selling Spanish property?', 'Sellers pay capital gains tax on profit, plus municipal capital gains tax (plusvalía) to the local council.', 'When selling Spanish property, you pay: 1) Capital Gains Tax: On profit made from sale. Non-residents pay 19% on gains, residents pay 19-23% depending on total income and length of ownership. 2) Municipal Capital Gains Tax (Plusvalía): Paid to local council, calculated on theoretical land value increase (typically €500-3,000). 3) Possible exemptions: Main residence sales may be exempt for residents over 65, or if reinvesting in new main residence. Always consult a tax advisor as recent law changes have made some plusvalía charges invalid.', 'taxes-selling-spanish-property', 'selling', ARRAY['taxes', 'capital gains', 'plusvalia', 'selling'], 'Costa del Sol', true, 2, 'Taxes When Selling Spanish Property: Complete Guide', 'Complete guide to all taxes payable when selling property in Spain including capital gains and plusvalía.', ARRAY['capital gains tax spain', 'selling property taxes', 'plusvalia tax'], ARRAY['what taxes selling property spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment', 'townhouse']),

-- Finance & Taxes FAQs (10 questions)
('en', 'What is the Golden Visa and how do I qualify?', 'Spain''s Golden Visa grants residency to non-EU investors who purchase property worth €500,000 or more.', 'Spain''s Golden Visa (Investor Visa) grants renewable residence permits to non-EU citizens investing €500,000+ in Spanish real estate. Benefits include: residence permits for investor, spouse, and children under 18; no minimum stay requirement; travel freedom within Schengen area; potential path to permanent residency after 5 years. Requirements: clean criminal record, health insurance, proof of funds, maintain investment. The property can be residential or commercial, single or multiple properties totaling €500,000+. Processing takes 2-4 months and costs around €5,000 in fees.', 'spanish-golden-visa-requirements', 'finance', ARRAY['golden visa', 'residency', 'investment', 'visa'], 'Costa del Sol', true, 1, 'Spain Golden Visa: Requirements and Benefits Guide', 'Complete guide to Spain''s Golden Visa program for property investors including requirements and benefits.', ARRAY['spain golden visa', 'investor visa spain', 'residency visa'], ARRAY['what is spain golden visa', 'how to get golden visa spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment']),

-- Legal & Notary FAQs (8 questions)
('en', 'What happens at the notary signing?', 'The notary signing is the final step where ownership officially transfers, all parties sign the title deed, and keys are handed over.', 'The notary signing (Escritura de Compraventa) is the culmination of your Spanish property purchase. The notary, a public official, oversees the final transfer of ownership. Present are: buyer, seller, notary, and often lawyers/representatives. The notary reads the title deed in Spanish (translation available), verifies all parties'' identities, confirms payment of taxes and fees, registers the new ownership, and hands over the keys. The entire process takes 30-60 minutes. Bring your NIE, passport, bank transfer confirmations, and any required checks. After signing, the property is officially yours.', 'notary-signing-process-spain', 'legal', ARRAY['notary', 'signing', 'escritura', 'completion'], 'Costa del Sol', true, 1, 'Spanish Property Notary Signing: What to Expect', 'Complete guide to the Spanish property notary signing process and what happens on completion day.', ARRAY['notary signing spain', 'escritura signing', 'property completion'], ARRAY['what happens notary signing spain'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment', 'townhouse']),

-- Continue with remaining categories...
-- Viewing Trips, Residency & Visas, Lifestyle & Culture, Property Types, Timeline & Process, Technology
-- (Adding a few more key FAQs for completeness)

('en', 'How do I organize a property viewing trip to Costa del Sol?', 'Plan 3-4 days, book viewings in advance, arrange airport transfers, and consider hiring a buyer''s agent for guidance.', 'Organizing an effective Costa del Sol viewing trip: 1) Duration: Plan 3-4 days minimum to avoid rushed decisions. 2) Pre-planning: Research areas online, shortlist properties, book viewings in advance. 3) Logistics: Fly into Málaga airport, arrange car rental or transfers, book accommodation centrally. 4) Professional help: Consider hiring an independent buyer''s agent familiar with the area. 5) What to see: Visit different times of day, check local amenities, transport links, and seasonal variations. 6) Documentation: Bring passport, NIE number application, and bank statements if serious about purchasing.', 'organizing-property-viewing-trip', 'viewing', ARRAY['viewing trip', 'planning', 'costa del sol', 'travel'], 'Costa del Sol', true, 1, 'How to Organize a Costa del Sol Property Viewing Trip', 'Complete guide to planning an effective property viewing trip to Costa del Sol.', ARRAY['property viewing trip', 'costa del sol viewing', 'spain property visit'], ARRAY['how to plan property viewing trip spain'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['villa', 'apartment', 'townhouse']),

('en', 'What are the best areas to live in Costa del Sol?', 'Popular areas include Marbella for luxury, Estepona for authentic charm, Fuengirola for amenities, and Nerja for traditional Spanish feel.', 'Costa del Sol offers diverse living options: Marbella - luxury lifestyle, high-end shopping, glamorous nightlife, but premium prices. Estepona - authentic Spanish charm, beautiful old town, more affordable, great for families. Fuengirola - excellent amenities, transport links, international community, reasonable prices. Benalmádena - family-friendly, theme parks, marina, good value. Nerja - traditional Spanish atmosphere, stunning views, quieter pace. Torremolinos - vibrant nightlife, gay-friendly, budget-friendly. Mijas - hilltop village charm, golf courses, mixed Spanish-international community. Consider proximity to airport, healthcare, schools, and your lifestyle preferences.', 'best-areas-costa-del-sol', 'lifestyle', ARRAY['areas', 'locations', 'lifestyle', 'comparison'], 'Costa del Sol', true, 1, 'Best Areas to Live in Costa del Sol: Complete Guide', 'Comprehensive guide to the best areas and towns for living in Costa del Sol.', ARRAY['best areas costa del sol', 'where to live costa del sol', 'costa del sol locations'], ARRAY['where is best to live costa del sol'], ARRAY['Costa del Sol', 'Marbella', 'Estepona', 'Fuengirola'], ARRAY['villa', 'apartment']),

('en', 'What is Isabelle and how can she help me?', 'Isabelle is our AI property concierge providing 24/7 assistance with property searches, market insights, and personalized recommendations.', 'Isabelle is your intelligent property concierge, available 24/7 to assist with your Costa del Sol property journey. She can: provide instant property recommendations based on your criteria, offer real-time market insights and pricing analysis, schedule viewing appointments and coordinate logistics, answer questions about areas, amenities, and local services, connect you with trusted local professionals (lawyers, surveyors, mortgage brokers), provide multilingual support in 12+ languages, and offer personalized investment advice based on your goals. Simply chat with Isabelle through our website or WhatsApp for immediate, expert assistance tailored to your needs.', 'isabelle-ai-property-concierge', 'technology', ARRAY['AI', 'assistant', 'concierge', 'help'], 'Costa del Sol', true, 1, 'Meet Isabelle: Your AI Property Concierge', 'Learn how Isabelle, our AI property assistant, can help you find and buy property in Costa del Sol.', ARRAY['AI property assistant', 'property concierge', 'automated help'], ARRAY['what is isabelle ai assistant', 'how can isabelle help me'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment', 'townhouse']);