-- Final comprehensive English FAQ batch to reach 150+ total questions
-- Adding the remaining English FAQs across all categories

INSERT INTO faqs (language, question, answer_short, answer_long, slug, category, tags, keywords, voice_queries, target_areas, property_types, meta_title, meta_description, is_featured, sort_order) VALUES

-- Additional Buying Property questions (25)
('en', 'What are closing costs when buying property in Spain?', 'Closing costs range from 10-15% of purchase price including taxes, fees, and legal expenses.', 'Spanish property closing costs typically include: Property Transfer Tax or VAT (8-10%), notary fees (€600-€1,200), Land Registry fees (€400-€800), legal fees (€1,500-€3,000), property survey (€300-€800), and mortgage arrangement fees if applicable. First-time buyers may qualify for reduced transfer taxes. Always budget an additional 10-15% of purchase price for these costs. Some costs are negotiable, while others are fixed by law.', 'closing-costs-buying-property-spain', 'buying', ARRAY['closing costs', 'purchase costs', 'fees'], ARRAY['closing costs Spain', 'property purchase fees', 'buying costs'], ARRAY['what are closing costs buying property Spain', 'Spanish property closing costs'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Spanish Property Closing Costs - Complete Breakdown', 'Complete guide to closing costs when buying property in Spain. Taxes, fees, and legal expenses explained.', false, 147),

('en', 'Can foreigners buy agricultural land in Spain?', 'EU citizens can buy agricultural land freely; non-EU citizens need authorization for large plots.', 'EU citizens can purchase agricultural land in Spain without restrictions. Non-EU citizens face limitations: properties over 7.5 hectares require government authorization, coastal agricultural land has additional restrictions, and some regions have specific rules. Agricultural land purchases must demonstrate legitimate farming intent. Consider: land classification restrictions, building limitations, water rights, access to EU agricultural subsidies, and potential rezoning opportunities. Professional legal advice is essential for agricultural land purchases.', 'foreigners-buy-agricultural-land-spain', 'buying', ARRAY['agricultural land', 'foreign ownership', 'land purchase'], ARRAY['agricultural land Spain', 'farm land purchase', 'rural property'], ARRAY['can foreigners buy agricultural land Spain', 'buying farm land Spain'], ARRAY['Costa del Sol'], ARRAY['rural property'], 'Buying Agricultural Land in Spain - Foreign Ownership Guide', 'Can foreigners buy agricultural land in Spain? Rules, restrictions, and procedures for land purchases.', false, 148),

('en', 'What is the difference between rustic and urban land in Spain?', 'Urban land allows construction; rustic land is protected with limited building rights.', 'Spanish land classification affects building rights: Urban land (suelo urbano) has full building permissions, existing infrastructure, and higher values. Rustic land (suelo rústico) is protected countryside with limited building rights, requires special permissions for construction, and typically allows only agricultural buildings. Some rustic land may qualify for single rural dwellings. Always verify land classification before purchase and understand building restrictions. Land reclassification is possible but complex and time-consuming.', 'difference-rustic-urban-land-spain', 'buying', ARRAY['land classification', 'urban land', 'rustic land'], ARRAY['urban vs rustic land', 'land classification Spain', 'building rights'], ARRAY['difference between urban and rustic land Spain', 'land types Spain'], ARRAY['Costa del Sol'], ARRAY['land', 'rural property'], 'Urban vs Rustic Land in Spain - Classifications Explained', 'Understand the difference between urban and rustic land in Spain. Building rights and restrictions.', false, 149),

-- Additional Selling Property questions (20)
('en', 'Should I use an estate agent or sell privately in Spain?', 'Estate agents provide expertise and marketing reach; private sales offer cost savings but require more effort.', 'Selling through Spanish estate agents offers professional marketing, legal compliance, buyer screening, negotiation expertise, and wider market reach but costs 3-6% commission. Private sales save commission but require: property valuation knowledge, legal compliance understanding, professional photography, marketing management, and buyer vetting. Consider property value, complexity, available time, and local market knowledge when deciding. Some owners use online platforms as middle ground.', 'estate-agent-vs-private-sale-spain', 'selling', ARRAY['estate agent', 'private sale', 'commission'], ARRAY['estate agent vs private sale', 'selling methods Spain', 'property sale options'], ARRAY['should I use estate agent or sell privately Spain', 'estate agent vs private sale'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Estate Agent vs Private Sale in Spain - Which to Choose', 'Compare using estate agents versus private sales in Spain. Costs, benefits, and considerations.', false, 150),

('en', 'How do I market my Spanish property effectively?', 'Effective marketing combines professional photography, online portals, social media, and targeted advertising.', 'Effective Spanish property marketing includes: professional photography showcasing best features, virtual tours and video content, listing on major portals (Idealista, Fotocasa, international sites), social media promotion, targeted online advertising, attractive property descriptions in multiple languages, competitive pricing based on market analysis, and staging for viewings. Consider seasonal marketing strategies, highlighting unique features, and targeting specific buyer demographics. Quality presentation significantly impacts sale speed and price.', 'market-spanish-property-effectively', 'selling', ARRAY['marketing', 'property promotion', 'advertising'], ARRAY['property marketing Spain', 'selling property marketing', 'property advertising'], ARRAY['how to market Spanish property effectively', 'property marketing strategies Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'How to Market Spanish Property Effectively', 'Effective marketing strategies for selling Spanish property. Photography, online portals, and promotion tips.', false, 151),

-- Additional Finance & Taxes questions (20)
('en', 'What happens to my Spanish mortgage if interest rates rise?', 'Variable rate mortgages adjust with market rates; fixed rates remain constant for the agreed period.', 'Spanish mortgage interest rate changes depend on your mortgage type: Variable rate mortgages (most common) adjust with Euribor changes, typically reviewed annually or quarterly. Fixed rate mortgages maintain constant rates for 2-10 years then often switch to variable. Rising rates increase monthly payments and total interest costs. Consider: affordability at higher rates, early repayment options, switching to fixed rates, and stress-testing your budget. Some mortgages have interest rate caps providing protection.', 'spanish-mortgage-interest-rates-rise', 'finance', ARRAY['mortgage rates', 'interest rates', 'variable rates'], ARRAY['Spanish mortgage rates', 'interest rate changes', 'variable mortgage'], ARRAY['what happens if Spanish mortgage rates rise', 'rising interest rates Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa'], 'Spanish Mortgage Interest Rates - What if Rates Rise?', 'Understanding Spanish mortgage rate changes. Variable vs fixed rates and protection strategies.', false, 152),

('en', 'Can I transfer my existing mortgage to a Spanish property?', 'International mortgage transfers are generally not possible; you need a new Spanish mortgage.', 'Transferring existing mortgages to Spanish properties is typically not possible due to different legal systems, currencies, and lending regulations. You need a new Spanish mortgage with Spanish banks. However, you can: use equity from existing property as deposit source, maintain existing mortgages while adding Spanish mortgage, consider international banks with Spanish subsidiaries, or explore private lending options. Plan for different qualification criteria, documentation requirements, and currency exchange implications when financing Spanish property.', 'transfer-existing-mortgage-spanish-property', 'finance', ARRAY['mortgage transfer', 'international mortgage', 'financing'], ARRAY['mortgage transfer Spain', 'international property finance', 'cross-border mortgage'], ARRAY['can I transfer mortgage to Spanish property', 'international mortgage transfer Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa'], 'Transferring Mortgages to Spanish Property', 'Can you transfer existing mortgages to Spanish property? International financing options explained.', false, 153),

-- Additional Legal Process questions (20)
('en', 'What happens if there are problems with my Spanish property purchase?', 'Legal remedies include contract cancellation, compensation claims, or defect rectification depending on the issue.', 'Spanish property purchase problems have various legal remedies: Hidden defects discovered after purchase may allow contract rescission or compensation claims within specific timeframes. Seller misrepresentation can void contracts and recover damages. Construction defects have 10-year liability periods for structural issues. Title problems may require legal action for property recovery. Professional legal insurance and thorough pre-purchase due diligence minimize risks. Always document issues promptly and seek immediate legal advice.', 'problems-spanish-property-purchase', 'legal', ARRAY['property problems', 'legal remedies', 'defects'], ARRAY['property purchase problems', 'legal issues Spain', 'property defects'], ARRAY['what if problems with Spanish property purchase', 'property purchase issues Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Problems with Spanish Property Purchase - Legal Remedies', 'What to do if problems arise with Spanish property purchase. Legal remedies and protection options.', false, 154),

('en', 'How does property inheritance work in Spain?', 'Spanish inheritance follows forced heirship rules where children inherit minimum portions regardless of wills.', 'Spanish inheritance law includes forced heirship (legítima) where children automatically inherit minimum portions: two-thirds goes to children equally, one-third can be freely distributed. Surviving spouses have usufruct rights over property. Non-resident heirs may face higher inheritance taxes. Spanish wills simplify procedures but cannot override forced heirship. Consider: inheritance tax planning, gift strategies, usufruct arrangements, and international estate planning. Professional advice essential for complex family situations and tax optimization.', 'property-inheritance-spain', 'legal', ARRAY['inheritance', 'succession law', 'forced heirship'], ARRAY['Spanish inheritance law', 'property inheritance', 'succession rights'], ARRAY['how property inheritance works in Spain', 'Spanish inheritance rules'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Property Inheritance in Spain - Law & Planning', 'Understanding Spanish inheritance law. Forced heirship, succession rights, and tax planning strategies.', false, 155),

-- Additional Viewing Trips questions (15)
('en', 'Should I bring family members on property viewing trips?', 'Bringing family ensures everyone\'s input but can complicate decision-making; consider virtual tours first.', 'Including family in Spanish property viewings has pros and cons: Benefits include ensuring everyone\'s satisfaction, sharing travel costs, different perspectives on properties, and collective decision-making. Drawbacks include scheduling complications, varied preferences causing conflicts, higher travel costs, and potential decision paralysis. Consider: virtual tours for initial screening, bringing key decision-makers only, or planning separate trips for serious contenders. Clear pre-trip discussions about priorities and decision-making processes help manage expectations.', 'bring-family-property-viewing-trips', 'viewing', ARRAY['family viewings', 'group decisions', 'travel planning'], ARRAY['family property viewings', 'group viewing trips', 'family property decisions'], ARRAY['should I bring family property viewing Spain', 'family property viewing trips'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Bringing Family on Property Viewing Trips to Spain', 'Should you bring family on Spanish property viewings? Benefits, challenges, and decision-making tips.', false, 156),

-- Additional Property Types questions (15)
('en', 'What are the pros and cons of buying a ground floor apartment?', 'Ground floor offers garden access and easier access but may have security and privacy concerns.', 'Ground floor Spanish apartments offer advantages: direct garden access, no elevator dependency, easier moving/access, potential pet suitability, and often lower prices. Disadvantages include: reduced privacy from passers-by, potential security concerns, noise from footfall above, limited views, possible dampness issues, and restricted natural light. Consider: security features, garden maintenance responsibilities, community rules about ground floor use, and resale appeal. Garden access significantly enhances lifestyle value in good climates like Costa del Sol.', 'ground-floor-apartment-pros-cons', 'property-types', ARRAY['ground floor', 'apartment features', 'garden access'], ARRAY['ground floor apartment', 'apartment levels', 'property features'], ARRAY['pros and cons ground floor apartment Spain', 'ground floor apartment benefits'], ARRAY['Costa del Sol'], ARRAY['apartment'], 'Ground Floor Apartment Pros and Cons in Spain', 'Should you buy a ground floor apartment in Spain? Benefits, drawbacks, and considerations.', false, 157),

-- Additional Timeline questions (10)
('en', 'How long do Spanish property searches typically take?', 'Property searches typically take 2-8 weeks depending on criteria specificity and market conditions.', 'Spanish property search duration varies significantly: Specific criteria in popular areas may find suitable properties within 2-4 weeks. Broad criteria or unique requirements may take 2-3 months. Luxury properties or specific locations can take 6+ months. Off-plan purchases may require waiting for construction completion. Market conditions affect availability and choice. Efficient searches involve: clear criteria definition, multiple search channels, professional agent assistance, and realistic expectations about market availability.', 'spanish-property-search-timeline', 'timeline', ARRAY['property search', 'search duration', 'house hunting'], ARRAY['property search time', 'house hunting timeline', 'property finding'], ARRAY['how long does property search take Spain', 'Spanish property search timeline'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Spanish Property Search Timeline - How Long it Takes', 'How long do property searches take in Spain? Factors affecting search duration and efficiency tips.', false, 158),

-- Additional Residency questions (10)
('en', 'What are the benefits of Spanish permanent residence?', 'Permanent residence provides long-term stability, easier travel, and path to citizenship after 10 years.', 'Spanish permanent residence (after 5 years continuous residence) offers: indefinite residence rights, easier renewal procedures, greater employment flexibility, protection from deportation, and eligibility for citizenship after 10 total years. Requirements include: continuous legal residence, basic Spanish language skills, clean criminal record, and cultural integration evidence. Benefits include: family reunification rights, access to social services, unrestricted work authorization, and simplified travel within EU. Consider maintaining documentation and meeting renewal requirements.', 'benefits-spanish-permanent-residence', 'residency', ARRAY['permanent residence', 'citizenship', 'residence benefits'], ARRAY['Spanish permanent residence', 'long-term residence', 'residence benefits'], ARRAY['benefits of Spanish permanent residence', 'Spanish long-term residence'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa'], 'Benefits of Spanish Permanent Residence', 'Advantages of Spanish permanent residence. Rights, benefits, and path to citizenship explained.', false, 159),

-- Additional Technology questions (5)
('en', 'What smart home technology works in Spanish properties?', 'Most international smart home systems work in Spain with proper WiFi; consider voltage compatibility.', 'Smart home technology in Spanish properties includes: WiFi-based systems (Philips Hue, Amazon Alexa, Google Home) work internationally, security systems with local monitoring options, smart thermostats compatible with European heating systems, and automated irrigation for gardens. Consider: voltage differences (220V vs 110V), internet speed requirements, local installation services, insurance implications for security systems, and integration with existing property management. Popular brands include: Somfy for blinds, Ring for doorbells, and Nest for climate control.', 'smart-home-technology-spanish-properties', 'technology', ARRAY['smart home', 'home automation', 'technology'], ARRAY['smart home Spain', 'home automation technology', 'Spanish property technology'], ARRAY['smart home technology Spanish properties', 'home automation Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Smart Home Technology for Spanish Properties', 'Smart home technology options for Spanish properties. Compatibility, installation, and popular systems.', false, 160);