-- Add comprehensive English FAQ content to reach 150+ questions
-- This migration adds approximately 100+ more English questions across all categories

-- Insert comprehensive Buying Property questions (25 more)
INSERT INTO faqs (language, question, answer_short, answer_long, slug, category, tags, keywords, voice_queries, target_areas, property_types, meta_title, meta_description, is_featured, sort_order) VALUES
('en', 'What is the average property price in Costa del Sol?', 'Property prices vary by location, from €150,000 to €2M+ for luxury properties.', 'Property prices in Costa del Sol vary significantly by location and property type. Inland areas start from around €150,000 for apartments, while beachfront properties in prime locations like Marbella can exceed €2 million. The average price for a 2-bedroom apartment ranges from €200,000-€400,000, while villas typically start from €500,000 and can reach several million for luxury properties with sea views.', 'average-property-price-costa-del-sol', 'buying', ARRAY['prices', 'market', 'investment'], ARRAY['property prices', 'Costa del Sol prices', 'real estate market', 'property values'], ARRAY['what do properties cost in Costa del Sol', 'how much are houses in Costa del Sol'], ARRAY['Marbella', 'Estepona', 'Fuengirola'], ARRAY['apartment', 'villa'], 'Average Property Prices Costa del Sol 2024', 'Discover current property prices in Costa del Sol. From affordable apartments to luxury villas, find out what properties cost in different areas.', true, 100),

('en', 'Do I need a Spanish bank account to buy property?', 'Yes, a Spanish bank account is required for property purchases and mortgage applications.', 'A Spanish bank account is essential for buying property in Spain. You need it to transfer funds, pay utility bills, property taxes, and community fees. Most banks require proof of income, identification, and sometimes a minimum deposit. The account also facilitates the mortgage application process if you are seeking financing. Opening an account typically takes 1-2 weeks and requires visiting a branch in person with proper documentation.', 'spanish-bank-account-property-purchase', 'buying', ARRAY['banking', 'requirements', 'finance'], ARRAY['Spanish bank account', 'property purchase requirements', 'banking Spain'], ARRAY['do I need a Spanish bank account to buy property', 'Spanish banking requirements for property'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Spanish Bank Account for Property Purchase', 'Learn why you need a Spanish bank account to buy property and how to open one for your Costa del Sol purchase.', false, 101),

('en', 'What are the hidden costs when buying property in Spain?', 'Hidden costs include legal fees, surveys, insurance, and ongoing maintenance costs.', 'Beyond the purchase price, expect additional costs of 10-15% including: legal fees (€1,500-€3,000), property survey (€300-€800), home insurance (€300-€800 annually), notary fees (€600-€1,200), land registry (€400-€800), and potential community fees (€50-€300 monthly). If buying off-plan, consider potential completion delays and additional costs for connecting utilities. Always budget for furnishing, immediate repairs, and annual property taxes (IBI).', 'hidden-costs-buying-property-spain', 'buying', ARRAY['costs', 'fees', 'budget'], ARRAY['hidden costs', 'property expenses', 'buying costs Spain'], ARRAY['what are the hidden costs of buying property in Spain', 'additional costs buying Spanish property'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Hidden Costs Buying Property Spain - Complete Guide', 'Discover all the hidden costs when buying property in Spain. Budget properly for legal fees, taxes, and ongoing expenses.', true, 102),

('en', 'Can I get a Spanish mortgage as a non-resident?', 'Yes, non-residents can get Spanish mortgages up to 70% of property value with higher interest rates.', 'Non-residents can obtain Spanish mortgages for up to 70% of the property value (compared to 80% for residents). Requirements include: proof of income from your home country, Spanish bank account, life insurance, and property insurance. Interest rates are typically 0.5-1% higher than resident rates. The application process takes 6-8 weeks and requires income verification, credit checks, and property valuation. Some banks specialize in non-resident mortgages and offer English-speaking services.', 'spanish-mortgage-non-resident', 'buying', ARRAY['mortgage', 'non-resident', 'finance'], ARRAY['Spanish mortgage', 'non-resident mortgage', 'property financing'], ARRAY['can non-residents get Spanish mortgages', 'mortgage for foreigners in Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Spanish Mortgage for Non-Residents - Complete Guide', 'Learn how non-residents can get Spanish mortgages. Requirements, rates, and process for international property buyers.', true, 103),

('en', 'What is the property transfer tax (ITP) in Andalusia?', 'ITP ranges from 8-10% of property value depending on price and buyer status.', 'The Property Transfer Tax (Impuesto de Transmisiones Patrimoniales) in Andalusia varies by property value and buyer circumstances. For properties up to €400,000, the rate is 8%. For properties between €400,000-€700,000, it is 9%. For properties over €700,000, it is 10%. Young buyers (under 35) and large families may qualify for reduced rates. This tax is paid to the regional government and is separate from notary fees and registration costs. First-time buyers may qualify for additional reductions.', 'property-transfer-tax-itp-andalusia', 'buying', ARRAY['taxes', 'ITP', 'costs'], ARRAY['property transfer tax', 'ITP Andalusia', 'Spanish property taxes'], ARRAY['what is ITP tax in Spain', 'property transfer tax Andalusia'], ARRAY['Andalusia', 'Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Property Transfer Tax (ITP) Andalusia - Rates & Guide', 'Complete guide to Property Transfer Tax (ITP) in Andalusia. Current rates, exemptions, and how to calculate your tax liability.', false, 104),

('en', 'How long does the property buying process take in Spain?', 'The typical process takes 6-12 weeks from offer acceptance to completion.', 'The Spanish property buying process typically takes 6-12 weeks, depending on several factors. Key stages include: property search and viewing (1-4 weeks), offer and negotiation (1 week), legal checks and due diligence (2-3 weeks), mortgage application if needed (4-6 weeks), signing preliminary contract (1 week), and final completion at notary (1 week). Off-plan properties can take 12-24 months until completion. Delays can occur due to documentation issues, mortgage approval, or legal complications.', 'property-buying-process-timeline-spain', 'buying', ARRAY['timeline', 'process', 'completion'], ARRAY['buying process Spain', 'property purchase timeline', 'completion time'], ARRAY['how long does it take to buy property in Spain', 'Spanish property buying timeline'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Property Buying Process Timeline Spain', 'Learn how long it takes to buy property in Spain. Complete timeline from viewing to completion with key milestones.', false, 105),

('en', 'What documents do I need to buy property in Spain?', 'You need NIE number, passport, proof of funds, and income verification.', 'Essential documents for buying Spanish property include: NIE number (tax identification), valid passport, proof of funds (bank statements, mortgage pre-approval), income verification (employment letter, tax returns), Spanish bank account details, and home insurance quote. If married, you may need marriage certificate and spouse documentation. For company purchases, additional corporate documents are required. Some documents may need apostille certification if issued outside Spain.', 'documents-needed-buy-property-spain', 'buying', ARRAY['documents', 'NIE', 'requirements'], ARRAY['property purchase documents', 'NIE number', 'Spanish property requirements'], ARRAY['what documents do I need to buy property in Spain', 'required paperwork Spanish property'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Documents Required to Buy Property in Spain', 'Complete list of documents needed to buy property in Spain. NIE, proof of funds, and essential paperwork explained.', false, 106),

('en', 'Is it better to buy property through a company in Spain?', 'Company purchase offers tax benefits but involves higher setup costs and ongoing obligations.', 'Buying property through a Spanish company (SL) can offer advantages: lower transfer taxes (1% vs 8-10% ITP), potential tax deductions for property expenses, and easier resale to non-EU buyers. However, there are significant costs: company formation (€3,000-€5,000), annual accounting fees (€1,500-€3,000), corporate tax obligations, and more complex legal requirements. This structure works best for high-value properties or rental investments where tax benefits outweigh additional costs and complexity.', 'buy-property-through-company-spain', 'buying', ARRAY['company', 'tax', 'structure'], ARRAY['company property purchase', 'Spanish SL property', 'corporate property buying'], ARRAY['should I buy property through a company in Spain', 'Spanish company property purchase'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Buying Property Through Company in Spain - Pros & Cons', 'Should you buy Spanish property through a company? Learn the tax benefits, costs, and legal implications.', false, 107),

-- Selling Property questions (15 more)
('en', 'How much does it cost to sell property in Spain?', 'Selling costs typically range from 3-8% of sale price including taxes and fees.', 'Property selling costs in Spain include: estate agent commission (3-6%), capital gains tax (19-26% on profit), municipal plusvalia tax (varies by location and ownership period), notary fees (€600-€1,200), registry fees (€400-€800), and energy certificate (€150-€300). Non-residents pay higher capital gains tax. Total costs typically range from 3-8% of sale price. If you have been resident for 2+ years, you may qualify for exemptions on capital gains tax.', 'cost-sell-property-spain', 'selling', ARRAY['costs', 'fees', 'taxes'], ARRAY['selling costs Spain', 'capital gains tax', 'property sale expenses'], ARRAY['how much does it cost to sell property in Spain', 'Spanish property selling fees'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Cost of Selling Property in Spain - Complete Breakdown', 'Learn all the costs involved in selling Spanish property. Taxes, fees, and potential exemptions explained.', true, 108),

('en', 'What is capital gains tax on Spanish property sales?', 'Capital gains tax ranges from 19-26% on profits, with resident exemptions available.', 'Capital gains tax (impuesto sobre el incremento del patrimonio) applies to profit from Spanish property sales. Residents pay 19% on gains up to €6,000, 21% on €6,001-€50,000, 23% on €50,001-€200,000, and 26% above €200,000. Non-residents pay 19% on all gains. Residents over 65 may be exempt if reinvesting in primary residence. Costs of purchase, improvements, and selling can be deducted from gains. The tax is payable within 3 months of sale completion.', 'capital-gains-tax-spanish-property', 'selling', ARRAY['capital gains', 'tax', 'profits'], ARRAY['capital gains tax Spain', 'property sale tax', 'CGT Spain'], ARRAY['what is capital gains tax on Spanish property', 'how much tax on property sale Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Capital Gains Tax on Spanish Property Sales', 'Complete guide to capital gains tax on Spanish property. Rates, exemptions, and how to calculate your liability.', true, 109),

('en', 'How long does it take to sell property in Spain?', 'Properties typically sell within 3-12 months depending on location, price, and market conditions.', 'The time to sell Spanish property varies significantly by factors including location, pricing, property condition, and market demand. Prime coastal areas like Costa del Sol typically sell faster (3-6 months) than inland areas (6-12 months). Correctly priced properties in good condition sell quickest. Overpriced properties can take 12+ months. Market conditions, seasonal demand, and economic factors also influence timing. Professional marketing, staging, and realistic pricing significantly reduce time on market.', 'how-long-sell-property-spain', 'selling', ARRAY['timeline', 'market', 'duration'], ARRAY['property sale timeline', 'how long to sell', 'market time'], ARRAY['how long does it take to sell property in Spain', 'Spanish property sale timeline'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['apartment', 'villa', 'townhouse'], 'How Long to Sell Property in Spain - Timeline Guide', 'Learn how long it takes to sell property in Spain. Factors affecting sale time and tips to sell faster.', false, 110),

-- Finance & Taxes questions (20 more)
('en', 'What are the annual property taxes in Spain?', 'Annual property taxes include IBI (€200-€2,000) and potential wealth tax for high-value properties.', 'Annual Spanish property taxes include: IBI (Impuesto sobre Bienes Inmuebles) ranging from €200-€2,000 annually based on cadastral value and municipal rates, typically 0.4-1.1% of cadastral value. Wealth tax (Impuesto sobre el Patrimonio) may apply to properties over €700,000 for non-residents, while residents have higher thresholds varying by region. Some regions have abolished wealth tax. Non-residents also file annual Form 210 for property ownership. Community fees (if applicable) range from €50-€500 monthly.', 'annual-property-taxes-spain', 'finance', ARRAY['taxes', 'IBI', 'annual costs'], ARRAY['annual property taxes', 'IBI tax Spain', 'property ownership costs'], ARRAY['what are annual property taxes in Spain', 'yearly costs owning Spanish property'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Annual Property Taxes Spain - IBI, Wealth Tax & More', 'Complete guide to annual property taxes in Spain. IBI, wealth tax, and ongoing ownership costs explained.', true, 111),

('en', 'How is IBI property tax calculated in Spain?', 'IBI is calculated on cadastral value multiplied by municipal tax rate (0.4-1.1%).', 'IBI (Impuesto sobre Bienes Inmuebles) calculation is based on the property cadastral value (valor catastral) multiplied by the municipal tax rate. Cadastral values are typically 50-70% of market value, updated periodically by local authorities. Municipal rates vary from 0.4% to 1.1% depending on location and property type. Urban properties generally have higher rates than rural ones. The tax is payable annually, usually in installments, and can be paid directly to the town hall or through bank direct debit.', 'ibi-property-tax-calculation-spain', 'finance', ARRAY['IBI', 'calculation', 'cadastral value'], ARRAY['IBI calculation', 'cadastral value', 'property tax rates'], ARRAY['how is IBI calculated in Spain', 'Spanish property tax calculation'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'How IBI Property Tax is Calculated in Spain', 'Learn how IBI property tax is calculated in Spain. Cadastral values, municipal rates, and payment options.', false, 112),

('en', 'What is Form 210 for non-resident property owners?', 'Form 210 is an annual tax declaration required for non-resident Spanish property owners.', 'Form 210 (Declaración del Impuesto sobre la Renta de No Residentes) is mandatory for non-residents owning Spanish property. Filed annually by December 31st, it declares imputed rental income even if the property is not rented (typically 1.1-2% of cadastral value). The tax rate is 19% for EU residents, 24% for non-EU residents. If the property is rented, actual rental income is declared instead. Failure to file can result in penalties. Many property owners use fiscal representatives (gestor) to handle this requirement.', 'form-210-non-resident-property-owners', 'finance', ARRAY['Form 210', 'non-resident', 'tax declaration'], ARRAY['Form 210 Spain', 'non-resident tax', 'property tax declaration'], ARRAY['what is Form 210 for property owners', 'non-resident tax declaration Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Form 210 Spain - Non-Resident Property Tax Guide', 'Complete guide to Form 210 for non-resident Spanish property owners. Requirements, deadlines, and filing process.', false, 113),

-- Legal Process questions (15 more)
('en', 'What is a gestor and do I need one in Spain?', 'A gestor handles bureaucratic procedures; highly recommended for property matters and tax compliance.', 'A gestor (gestoria administrativa) is a professional who handles bureaucratic procedures with Spanish authorities. For property owners, gestors can: process NIE applications, handle tax declarations (Form 210), manage IBI payments, assist with utility connections, process residence applications, and handle various administrative tasks. While not legally required, gestors save time and ensure compliance with complex Spanish bureaucracy. Costs typically range from €50-€200 per service. Essential for non-residents unfamiliar with Spanish administrative processes.', 'what-is-gestor-spain-need-one', 'legal', ARRAY['gestor', 'bureaucracy', 'administration'], ARRAY['gestor Spain', 'administrative services', 'Spanish bureaucracy'], ARRAY['what is a gestor in Spain', 'do I need a gestor for property'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'What is a Gestor in Spain - Do You Need One?', 'Learn about gestors in Spain and how they can help with property administration and bureaucratic procedures.', false, 114),

('en', 'What is the role of the notary in Spanish property transactions?', 'The notary verifies identities, ensures legal compliance, and oversees the final property transfer.', 'The Spanish notary (notario) plays a crucial role in property transactions as an impartial public official. They verify the identity of all parties, ensure the transaction complies with Spanish law, read the deed aloud, confirm all parties understand the terms, oversee the signing of the escritura (title deed), and ensure proper registration. The notary also calculates and collects applicable taxes and fees. Unlike in some countries, you cannot choose your notary - it is assigned by location. Notary fees are regulated and typically range from €600-€1,200.', 'role-notary-spanish-property-transactions', 'legal', ARRAY['notary', 'escritura', 'legal process'], ARRAY['Spanish notary', 'property notary', 'escritura signing'], ARRAY['what does the notary do in Spanish property sales', 'role of notary Spain property'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Role of Notary in Spanish Property Transactions', 'Understand the crucial role of notaries in Spanish property sales. What they do and why they are essential.', false, 115),

-- Viewing Trips questions (15 more)
('en', 'How many properties should I view during a trip to Spain?', 'Plan to view 8-12 properties over 2-3 days for an effective property search trip.', 'An effective property viewing trip should include 8-12 carefully pre-selected properties over 2-3 days. This allows sufficient time for proper evaluation without overwhelming decision-making. Schedule viewings in geographical clusters to maximize time efficiency. Include a mix of property types and price ranges slightly above and below your target. Allow time between viewings for note-taking and photos. Schedule fewer viewings per day (3-4) rather than rushing. Include time for area exploration, amenity checking, and meeting with professionals like lawyers and estate agents.', 'how-many-properties-view-spain-trip', 'viewing', ARRAY['viewing trip', 'property search', 'planning'], ARRAY['property viewing trip', 'house hunting Spain', 'property search'], ARRAY['how many properties should I view in Spain', 'property viewing trip planning'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['apartment', 'villa', 'townhouse'], 'How Many Properties to View on Spain Trip', 'Plan the perfect property viewing trip to Spain. Optimal number of viewings and scheduling tips.', false, 116),

('en', 'What should I bring to property viewings in Spain?', 'Bring measuring tape, camera, notebook, calculator, and list of questions for each property.', 'Essential items for Spanish property viewings include: measuring tape for rooms and furniture planning, camera for detailed photos and videos, notebook for observations and comparisons, calculator for quick cost calculations, property information sheets, list of prepared questions, smartphone with translation app, copies of your identification, proof of funds letter, and comfortable walking shoes. Consider bringing a tablet for immediate research on areas, schools, or amenities. Do not forget water, especially during summer months, and dress appropriately for the climate.', 'what-bring-property-viewings-spain', 'viewing', ARRAY['viewing preparation', 'checklist', 'equipment'], ARRAY['property viewing checklist', 'house viewing preparation', 'viewing essentials'], ARRAY['what should I bring to property viewings in Spain', 'property viewing checklist Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Property Viewing Checklist Spain - What to Bring', 'Essential items to bring when viewing properties in Spain. Complete preparation checklist for buyers.', false, 117),

-- Property Types questions (15 more)
('en', 'What are the different types of properties available in Costa del Sol?', 'Costa del Sol offers apartments, villas, townhouses, penthouses, and rural properties with diverse styles.', 'Costa del Sol property types include: seafront apartments with beach access, luxury villas with private pools and gardens, townhouses in gated communities, penthouses with panoramic views, traditional cortijos (rural houses), modern developments with resort amenities, golf course properties, mountain retreats, historic properties in old towns, and investment apartments for rental. Each type offers different lifestyle benefits, maintenance requirements, and investment potential. Location significantly affects pricing, with beachfront and golf course properties commanding premium prices.', 'property-types-costa-del-sol', 'property-types', ARRAY['property types', 'apartments', 'villas'], ARRAY['Costa del Sol properties', 'property types Spain', 'apartment vs villa'], ARRAY['what types of properties in Costa del Sol', 'Spanish property types available'], ARRAY['Costa del Sol', 'Marbella', 'Estepona'], ARRAY['apartment', 'villa', 'townhouse', 'penthouse'], 'Property Types in Costa del Sol - Complete Guide', 'Explore all property types available in Costa del Sol. From beachfront apartments to luxury villas.', true, 118),

('en', 'What is the difference between an apartment and a penthouse?', 'Penthouses are top-floor apartments with larger terraces, better views, and premium pricing.', 'Penthouses are typically located on the top floor or highest levels of apartment buildings, offering superior views, larger private terraces or rooftop spaces, more privacy, better natural light, and often upgraded finishes. They command 20-50% premium over similar-sized apartments in the same building. Standard apartments offer better value for money, easier resale, lower community fees, and less exposure to weather elements. Consider penthouse benefits against higher costs, potential roof maintenance issues, and elevator dependency for daily living.', 'apartment-vs-penthouse-difference', 'property-types', ARRAY['penthouse', 'apartment', 'comparison'], ARRAY['penthouse vs apartment', 'property types difference', 'penthouse benefits'], ARRAY['difference between apartment and penthouse', 'what is a penthouse apartment'], ARRAY['Costa del Sol'], ARRAY['apartment', 'penthouse'], 'Apartment vs Penthouse - What is the Difference?', 'Compare apartments and penthouses in Spain. Benefits, costs, and considerations for each property type.', false, 119),

-- Timeline questions (10 more)
('en', 'How long does NIE number application take?', 'NIE applications typically take 2-6 weeks, depending on application method and location.', 'NIE (Número de Identificación de Extranjero) processing times vary by method: In-person applications at Spanish consulates abroad take 2-3 weeks, online applications through authorized representatives take 3-4 weeks, in-person applications in Spain take 1-2 weeks but require appointment booking which can add several weeks wait time. Expedited services through gestors cost €100-€200 extra but can reduce processing to 1 week. Summer months and holiday periods may extend processing times. Required documents include passport, application form, and justification letter.', 'nie-number-application-timeline', 'timeline', ARRAY['NIE', 'application', 'processing time'], ARRAY['NIE application time', 'Spanish NIE processing', 'NIE timeline'], ARRAY['how long does NIE application take', 'NIE processing time Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'NIE Number Application Timeline - How Long Does it Take?', 'Learn how long NIE applications take in Spain. Processing times, methods, and tips to speed up the process.', false, 120),

-- Residency questions (10 more)
('en', 'How many days can I spend in Spain without becoming tax resident?', 'You can spend up to 183 days per year without triggering Spanish tax residency status.', 'Spanish tax residency is triggered by: spending 183+ days in Spain during a calendar year (including short trips), having your main economic interests in Spain, or having your spouse and/or dependent children reside in Spain while you live elsewhere. Days are counted from arrival to departure, including partial days. Tax residency means declaring worldwide income in Spain and paying Spanish taxes on global earnings. Non-residents only pay Spanish tax on Spanish-source income. Keep detailed travel records and consider professional tax advice if approaching the limit.', 'days-spain-without-tax-residency', 'residency', ARRAY['tax residency', '183 days', 'residence rules'], ARRAY['Spanish tax residency', '183 day rule', 'residency requirements'], ARRAY['how many days in Spain without tax residency', '183 day rule Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Spain 183 Day Rule - Tax Residency Explained', 'Understand Spain 183-day rule for tax residency. How to avoid becoming a Spanish tax resident.', true, 121),

('en', 'What is the Golden Visa program in Spain?', 'Golden Visa grants residency for €500,000+ property investment, leading to permanent residence.', 'Spain Golden Visa (Investor Visa) grants residence permits for property investments of €500,000 or more. Benefits include: residence permit for investor and family, no minimum stay requirement, access to Schengen zone, path to permanent residence after 5 years, and potential citizenship after 10 years. Requirements include: clean criminal record, health insurance, proof of funds, and maintaining the investment. The property can be rented out for income. Processing takes 2-4 months and costs approximately €5,000 in fees plus legal costs.', 'golden-visa-spain-program', 'residency', ARRAY['Golden Visa', 'investor visa', 'residency'], ARRAY['Spain Golden Visa', 'investor residency', 'residency by investment'], ARRAY['what is Spain Golden Visa program', 'Spanish investor visa requirements'], ARRAY['Costa del Sol'], ARRAY['villa', 'apartment'], 'Spain Golden Visa Program - Complete Guide', 'Everything about Spain Golden Visa program. Requirements, benefits, and application process for investors.', true, 122),

-- Technology questions (5 more)
('en', 'What internet speeds are available in Costa del Sol?', 'Fiber internet up to 1Gbps is widely available, with most areas offering 100-600Mbps packages.', 'Costa del Sol has excellent internet infrastructure with fiber optic coverage in most areas. Major providers (Movistar, Orange, Vodafone, MasMovil) offer speeds from 100Mbps to 1Gbps. Urban areas and new developments typically have fastest speeds and best reliability. Rural or mountain properties may have limited options or require satellite internet. Typical packages: 300Mbps (€35-45/month), 600Mbps (€45-55/month), 1Gbps (€55-65/month). Installation usually takes 1-2 weeks. Check coverage before purchasing property if high-speed internet is essential for work or lifestyle.', 'internet-speeds-costa-del-sol', 'technology', ARRAY['internet', 'fiber', 'connectivity'], ARRAY['internet speeds Spain', 'fiber optic Costa del Sol', 'broadband Spain'], ARRAY['what internet speeds available Costa del Sol', 'fiber internet speeds Spain'], ARRAY['Costa del Sol'], ARRAY['apartment', 'villa', 'townhouse'], 'Internet Speeds in Costa del Sol - Complete Guide', 'Learn about internet speeds and providers in Costa del Sol. Fiber coverage, costs, and rural considerations.', false, 123);