-- Continue adding comprehensive English FAQs - Part 4

INSERT INTO public.faqs (
  language, question, answer_short, answer_long, slug, category, tags, 
  keywords, voice_queries, target_areas, property_types, is_featured, sort_order
) VALUES

-- Real Estate Process FAQs
('en', 'How long does the property buying process take in Spain?', 
'The buying process typically takes 6-12 weeks from offer acceptance to completion.',
'The Spanish property buying process involves several stages: initial offer and negotiation (1-2 weeks), reservation contract and deposit (immediate), due diligence period including surveys and legal checks (2-4 weeks), mortgage application if needed (4-6 weeks), and final completion at the notary (1 week). The timeline can vary based on chain length, mortgage requirements, and any legal complications. Cash purchases are typically faster, completing in 4-8 weeks.',
'property-buying-process-timeline-spain', 'buying-process', 
ARRAY['buying process', 'property purchase', 'timeline', 'completion'],
ARRAY['buying process', 'property purchase', 'spain', 'timeline', 'legal', 'notary'],
ARRAY['how long to buy property in spain', 'spanish property buying timeline'],
ARRAY['Costa del Sol', 'Marbella', 'Estepona', 'Fuengirola'],
ARRAY['villa', 'apartment', 'townhouse', 'penthouse'], false, 40),

('en', 'What documents do I need to buy property in Spain?', 
'You need a NIE number, passport, proof of funds, and various legal documents.',
'Essential documents for buying Spanish property include: NIE number (foreigner identification number), valid passport, proof of funds (bank statements, mortgage pre-approval), Spanish bank account details, power of attorney if using a representative, building survey report, and legal title check results. Your lawyer will also require copies of the seller''s documents including title deeds, community fees certificates, and tax compliance certificates.',
'documents-needed-buy-property-spain', 'buying-process',
ARRAY['documents', 'NIE', 'legal requirements', 'paperwork'],
ARRAY['documents', 'NIE', 'passport', 'legal', 'requirements'],
ARRAY['what documents needed buy property spain', 'NIE number property purchase'],
ARRAY['Costa del Sol', 'Marbella', 'Estepona', 'Fuengirola'],
ARRAY['villa', 'apartment', 'townhouse', 'penthouse'], false, 41),

('en', 'Can I get a mortgage as a non-resident in Spain?', 
'Yes, non-residents can obtain mortgages up to 70% of property value with Spanish banks.',
'Non-residents can secure Spanish mortgages with several major banks including Banco Sabadell, BBVA, and Banco Santander. Typical terms include: maximum 70% loan-to-value ratio, 25-30 year terms, variable or fixed interest rates (currently 3-5%), minimum income requirements (usually €30,000+ annually), and proof of employment/income stability. Required documentation includes employment contracts, tax returns, bank statements, and property valuation. Some banks offer mortgages in foreign currencies.',
'non-resident-mortgage-spain-eligibility', 'financing',
ARRAY['mortgage', 'non-resident', 'financing', 'banks'],
ARRAY['mortgage', 'non-resident', 'financing', 'banks', 'loan'],
ARRAY['can non resident get mortgage spain', 'spanish mortgage for foreigners'],
ARRAY['Costa del Sol', 'Marbella', 'Estepona', 'Fuengirola'],
ARRAY['villa', 'apartment', 'townhouse', 'penthouse'], false, 42),

-- Property Features FAQs
('en', 'What is included in a typical Costa del Sol property sale?', 
'Sales typically include fitted kitchens, built-in wardrobes, and sometimes furniture packages.',
'Standard inclusions in Costa del Sol property sales vary but typically comprise: fitted kitchen with appliances (oven, hob, extractor), built-in wardrobes in bedrooms, air conditioning units, ceramic or marble flooring, bathroom fixtures and fittings, and exterior shutters. Many developments include communal amenities like pools and gardens. Furniture packages are sometimes available separately. Always verify specific inclusions in the purchase contract as standards vary between developers and resale properties.',
'what-included-costa-del-sol-property-sale', 'property-features',
ARRAY['inclusions', 'fixtures', 'fittings', 'furniture'],
ARRAY['inclusions', 'fixtures', 'fittings', 'kitchen', 'appliances'],
ARRAY['what included in spanish property sale', 'costa del sol property inclusions'],
ARRAY['Costa del Sol', 'Marbella', 'Estepona', 'Fuengirola', 'Benalmadena'],
ARRAY['villa', 'apartment', 'townhouse', 'penthouse'], false, 43),

('en', 'Are properties sold furnished or unfurnished in Spain?', 
'Most properties are sold unfurnished, but furniture packages are often available.',
'Spanish properties are predominantly sold unfurnished, allowing buyers to personalize their homes. However, many developers and sellers offer optional furniture packages ranging from €15,000-€50,000+ depending on property size and quality. These packages typically include: living room furniture, bedroom suites, dining sets, and soft furnishings. Some luxury developments include designer furniture packages. Rental properties are usually furnished. Always clarify furniture arrangements before purchase completion.',
'furnished-unfurnished-properties-spain', 'property-features',
ARRAY['furnished', 'unfurnished', 'furniture packages', 'interior'],
ARRAY['furnished', 'unfurnished', 'furniture', 'packages', 'interior'],
ARRAY['are spanish properties sold furnished', 'furniture packages spain property'],
ARRAY['Costa del Sol', 'Marbella', 'Estepona', 'Fuengirola'],
ARRAY['villa', 'apartment', 'townhouse', 'penthouse'], false, 44),

-- Neighborhood Insights
('en', 'Which areas of Costa del Sol are best for year-round living?', 
'Estepona, Fuengirola, and inland areas offer excellent year-round communities with local amenities.',
'Best year-round living areas combine international communities with Spanish authenticity: Estepona offers charming old town atmosphere with modern amenities and growing expat community. Fuengirola provides excellent transport links, healthcare, and established international schools. Inland areas like Mijas Pueblo offer authentic Spanish culture with lower costs. Benalmadena combines coastal living with practical amenities. These areas maintain active communities throughout winter months unlike purely seasonal resort areas.',
'best-areas-year-round-living-costa-del-sol', 'location-guides',
ARRAY['year-round living', 'permanent residence', 'communities', 'amenities'],
ARRAY['year-round', 'living', 'permanent', 'communities', 'amenities'],
ARRAY['best areas year round living costa del sol', 'permanent residence costa del sol'],
ARRAY['Estepona', 'Fuengirola', 'Mijas', 'Benalmadena'],
ARRAY['villa', 'apartment', 'townhouse'], true, 45),

('en', 'What is the difference between Marbella and Puerto Banús?', 
'Puerto Banús is a luxury marina district within Marbella municipality, known for superyachts and high-end shopping.',
'Puerto Banús is actually part of Marbella municipality, located about 6km southwest of Marbella center. Key differences: Puerto Banús is a purpose-built luxury marina from the 1970s featuring designer boutiques, superyacht berths, and premium restaurants. It''s more tourist-focused with seasonal crowds. Marbella city offers authentic Spanish culture, historic old town, year-round community, and more varied property options. Puerto Banús properties command premium prices due to marina proximity and prestige location.',
'difference-marbella-puerto-banus', 'location-guides',
ARRAY['Marbella', 'Puerto Banús', 'marina', 'luxury'],
ARRAY['Marbella', 'Puerto Banus', 'marina', 'luxury', 'differences'],
ARRAY['difference between marbella puerto banus', 'marbella vs puerto banus'],
ARRAY['Marbella', 'Puerto Banús'],
ARRAY['villa', 'apartment', 'penthouse'], false, 46),

-- Investment & Rental FAQs
('en', 'What rental yields can I expect on Costa del Sol property?', 
'Rental yields typically range from 4-7% annually, depending on location and property type.',
'Costa del Sol rental yields vary significantly by area and strategy: Prime beachfront locations (Marbella, Puerto Banús) achieve 4-5% annually with high-end guests. Popular family areas (Fuengirola, Torremolinos) can reach 6-7% with consistent bookings. Long-term rental yields are typically 4-5% but with less management intensity. Factors affecting yields include: seasonal vs year-round rentals, property condition and amenities, proximity to beaches and amenities, and local competition levels.',
'rental-yields-costa-del-sol-property', 'investment',
ARRAY['rental yields', 'investment returns', 'rental income'],
ARRAY['rental', 'yields', 'investment', 'income', 'returns'],
ARRAY['what rental yields costa del sol', 'costa del sol property investment returns'],
ARRAY['Costa del Sol', 'Marbella', 'Fuengirola', 'Torremolinos'],
ARRAY['villa', 'apartment', 'penthouse'], true, 47),

('en', 'Is short-term rental (Airbnb) legal in Costa del Sol?', 
'Short-term rentals are legal but require proper licensing and compliance with local regulations.',
'Short-term vacation rentals are legal in Costa del Sol with proper registration. Requirements include: obtaining a VFT (Vivienda de Fines Turísticos) license from Junta de Andalucía, meeting safety and habitability standards, registering with local town halls, displaying license numbers in all advertising, and maintaining guest registration records. Some communities may restrict short-term rentals in their bylaws. Penalties for unlicensed operation can be substantial. Professional property management companies can handle compliance requirements.',
'short-term-rental-legal-costa-del-sol', 'investment',
ARRAY['short-term rental', 'Airbnb', 'VFT license', 'regulations'],
ARRAY['short-term', 'rental', 'Airbnb', 'legal', 'license', 'VFT'],
ARRAY['is airbnb legal costa del sol', 'short term rental license spain'],
ARRAY['Costa del Sol', 'Marbella', 'Estepona', 'Fuengirola'],
ARRAY['villa', 'apartment', 'townhouse'], false, 48),

-- Infrastructure & Transport
('en', 'How good are transport links from Costa del Sol to other Spanish cities?', 
'Excellent transport connections include high-speed trains, motorways, and Málaga airport with domestic flights.',
'Costa del Sol enjoys exceptional connectivity: Málaga airport offers frequent domestic flights to Madrid (1h), Barcelona (1.5h), and other Spanish cities. The A-7 motorway provides direct access to Seville (2h), Granada (1.5h), and connects to national highway network. High-speed AVE train from Málaga reaches Madrid in 2.5 hours and Seville in 2 hours. Regional trains connect coastal towns. Bus services link to major cities affordably. This connectivity makes Costa del Sol an ideal base for exploring Spain.',
'transport-links-costa-del-sol-spanish-cities', 'infrastructure',
ARRAY['transport', 'connectivity', 'travel', 'trains', 'flights'],
ARRAY['transport', 'links', 'trains', 'flights', 'connectivity'],
ARRAY['transport links costa del sol spain', 'how to travel from costa del sol'],
ARRAY['Costa del Sol', 'Málaga'],
ARRAY['villa', 'apartment', 'townhouse'], false, 49),

('en', 'What internet and mobile coverage is like in Costa del Sol?', 
'Excellent fiber broadband and 4G/5G coverage throughout most areas, with some rural exceptions.',
'Costa del Sol has excellent digital infrastructure: Major coastal towns enjoy fiber broadband speeds up to 1Gbps from providers like Movistar, Vodafone, and Orange. 4G coverage is comprehensive with 5G increasingly available in urban areas. Rural inland properties may have limited options but satellite internet (Starlink) provides alternatives. Mobile coverage is excellent along the coast. Most modern developments include fiber infrastructure. Digital nomads and remote workers find connectivity reliable for professional use.',
'internet-mobile-coverage-costa-del-sol', 'infrastructure',
ARRAY['internet', 'broadband', 'mobile coverage', '5G', 'connectivity'],
ARRAY['internet', 'broadband', 'mobile', 'coverage', 'fiber'],
ARRAY['internet coverage costa del sol', 'broadband speed costa del sol'],
ARRAY['Costa del Sol', 'Marbella', 'Estepona', 'Fuengirola'],
ARRAY['villa', 'apartment', 'townhouse'], false, 50);